import { describe, expect, it } from 'vitest';
import { isLabUnlocked, labNetwork, labs } from '../content';
import { evaluateCheck, grade } from './grader';
import { applyPythonResult, executeHost, executeOn, type NetworkState, type PendingPython, type PythonResult } from './index';

/**
 * Python runs in the browser (Pyodide), not in vitest. Reference solutions for the Python
 * labs therefore get the result a correct script would produce, keyed by lab id.
 */
type Fake = (p: PendingPython) => Partial<PythonResult>;
let pythonFake: Fake = () => ({});
const py = (partial: Partial<PythonResult>): PythonResult => ({ stdout: '', stderr: '', exitCode: 0, files: {}, ...partial });

/** Reference-solution lines. "R2: cmd" or "PC-A: cmd" targets another node; default is the primary device. */
function run(net: NetworkState, ...lines: string[]): NetworkState {
  return lines.reduce((n, raw) => {
    const m = raw.match(/^([A-Za-z0-9-]+):\s*(.*)$/);
    const node = m && (n.devices[m[1]] || n.hosts[m[1]]) ? m[1] : n.primary;
    const line = m && node === m[1] ? m[2] : raw;
    if (!n.hosts[node]) return executeOn(n, node, line).network;
    const r = executeHost(n, node, line);
    return r.pending ? applyPythonResult(r.network, node, r.pending, py(pythonFake(r.pending))).network : r.network;
  }, net);
}

describe('lab unlock order', () => {
  it('opens labs one at a time as the previous lab is passed', () => {
    const [first, second, third] = labs;
    expect(isLabUnlocked(first.id, {})).toBe(true);
    expect(isLabUnlocked(second.id, {})).toBe(false);
    expect(isLabUnlocked(second.id, { [first.id]: { score: 100 } })).toBe(true);
    expect(isLabUnlocked(third.id, { [first.id]: { score: 100 } })).toBe(false);
  });

  it('gates each module on the last lab of the previous one', () => {
    const firstOfSecondModule = labs.find((l) => l.moduleId !== labs[0].moduleId)!;
    const lastOfFirstModule = labs[labs.indexOf(firstOfSecondModule) - 1];
    expect(lastOfFirstModule.moduleId).toBe(labs[0].moduleId);
    const allButLast = Object.fromEntries(labs.filter((l) => l.moduleId === labs[0].moduleId && l.id !== lastOfFirstModule.id).map((l) => [l.id, {}]));
    expect(isLabUnlocked(firstOfSecondModule.id, allButLast)).toBe(false);
    expect(isLabUnlocked(firstOfSecondModule.id, { ...allButLast, [lastOfFirstModule.id]: {} })).toBe(true);
  });
});

describe('labs are well formed', () => {
  it('have unique ids and at least one objective', () => {
    const ids = new Set(labs.map((l) => l.id));
    expect(ids.size).toBe(labs.length);
    for (const lab of labs) {
      expect(lab.objectives.length, lab.id).toBeGreaterThan(0);
      expect(() => labNetwork(lab), lab.id).not.toThrow();
    }
  });

  it('start with nothing passed', () => {
    for (const lab of labs) {
      expect(grade(lab.objectives, labNetwork(lab)).passed, lab.id).toBe(false);
    }
  });
});

describe('reference solutions pass', () => {
  const solutions: Record<string, string[]> = {
    'cli-01-first-contact': ['enable', '?', 'configure terminal'],
    'cli-02-give-it-a-name': ['en', 'conf t', 'hostname Branch-SW1', 'end', 'show running-config'],
    'cli-03-learning-from-errors': ['en', 'shwo running-config', 'sh st', 'conf t', 'hostname', 'do show running-config'],
    'cli-04-find-your-way-around': ['en', 'conf t', 'int g0/1', 'exit', 'vlan 10', 'end'],
    'cli-05-read-the-switch': ['en', 'show vlan brief', 'show interfaces status', 'show running-config', 'show ip interface brief'],
    'cli-06-save-your-work': ['en', 'conf t', 'hostname Floor2-SW1', 'end', 'show running-config', 'show startup-config', 'write memory', 'show startup-config'],
    'cli-07-lock-the-door': ['en', 'conf t', 'enable secret cisco123', 'line con 0', 'password conpass', 'login', 'line vty 0 4', 'password vtypass', 'login', 'end', 'show running-config'],
    'cli-08-who-gets-in': ['en', 'conf t', 'username admin privilege 15 secret Adm1n-Lab', 'line vty 0 4', 'login local', 'transport input ssh', 'end', 'write memory'],
    'cli-09-type-smart': ['en', 'conf t', 'int g0/1', 'do sh run', 'end', 'show running-config'],
    'cli-10-leave-a-note': ['en', 'conf t', 'banner motd # Authorized access only #', 'int g0/3', 'description Printer', 'end', 'show running-config'],
    'cli-11-test-investigate': ['en', 'show run', 'show vlan brief', 'show interfaces status', 'conf t', 'hostname Closet-SW2', 'vlan 10', 'name SALES', 'vlan 20', 'name HR', 'int g0/3', 'no shutdown', 'end', 'write memory'],
    'cli-12-exam-first-switch': ['en', 'conf t', 'hostname Remote-SW1', 'banner motd #Authorized personnel only#', 'enable secret R3mote!', 'line con 0', 'password c0nsole', 'login', 'exit', 'username netadmin privilege 15 secret N3t-adm1n', 'line vty 0 4', 'login local', 'end', 'copy running-config startup-config'],
    'sw-01-create-vlans': ['en', 'conf t', 'vlan 10', 'name SALES', 'vlan 20', 'name HR', 'end', 'show vlan brief'],
    'sw-02-assign-access-ports': ['en', 'conf t', 'int g0/1', 'switchport mode access', 'switchport access vlan 10', 'int g0/2', 'switchport mode access', 'switchport access vlan 20', 'do show vlan brief'],
    'sw-03-make-and-undo': ['en', 'conf t', 'vlan 30', 'vlan 40', 'do show vlan brief', 'no vlan 30', 'no vlan 40', 'do show vlan brief'],
    'sw-04-build-a-trunk': ['en', 'conf t', 'vlan 99', 'name NATIVE', 'int g0/6', 'switchport mode trunk', 'switchport trunk allowed vlan 10,20', 'switchport trunk native vlan 99', 'end', 'show interfaces trunk'],
    'sw-05-fix-the-trunk': ['en', 'show vlan brief', 'show interfaces trunk', 'conf t', 'int g0/1', 'switchport access vlan 10', 'int g0/6', 'switchport trunk allowed vlan add 10', 'end'],
    'sw-06-management-ip': ['en', 'conf t', 'int vlan 1', 'ip address 192.168.1.2 255.255.255.0', 'no shutdown', 'exit', 'ip default-gateway 192.168.1.1', 'end', 'ping 192.168.1.10'],
    'sw-07-who-is-plugged-in': ['en', 'show mac address-table', 'show interfaces status', 'conf t', 'int g0/3', 'description Printer', 'end'],
    'sw-08-native-vlan-mismatch': ['en', 'show interfaces trunk', 'conf t', 'vlan 99', 'name NATIVE', 'int g0/6', 'switchport trunk native vlan 99', 'end', 'show interfaces trunk'],
    'sw-09-management-vlan': ['en', 'conf t', 'int vlan 99', 'ip address 10.0.99.2 255.255.255.0', 'no shutdown', 'exit', 'ip default-gateway 10.0.99.1', 'end', 'ping 10.0.99.10'],
    'sw-10-trunk-cleanup': ['en', 'show interfaces trunk', 'conf t', 'int g0/6', 'switchport trunk allowed vlan remove 30,40', 'exit', 'no vlan 30', 'no vlan 40', 'end', 'show interfaces trunk'],
    'sw-11-exam-department-switch': ['en', 'conf t', 'hostname Dept-SW1', 'vlan 10', 'name SALES', 'vlan 20', 'name HR', 'vlan 99', 'name MGMT', 'int g0/1', 'switchport mode access', 'switchport access vlan 10', 'int g0/2', 'switchport mode access', 'switchport access vlan 20', 'int g0/8', 'switchport mode trunk', 'switchport trunk allowed vlan 10,20,99', 'switchport trunk native vlan 99', 'int vlan 99', 'ip address 10.0.99.5 255.255.255.0', 'no shutdown', 'exit', 'ip default-gateway 10.0.99.1', 'end', 'write memory'],
    'sec-01-encrypt-the-passwords': ['enable', 'cisco', 'conf t', 'enable secret S3cret!', 'service password-encryption', 'end', 'show running-config'],
    'sec-02-remote-access-ssh': ['en', 'conf t', 'ip domain-name lab.local', 'crypto key generate rsa modulus 2048', 'ip ssh version 2', 'username netadmin privilege 15 secret N3t-adm1n', 'line vty 0 4', 'login local', 'transport input ssh', 'end', 'show ip ssh'],
    'sec-03-park-unused-ports': ['en', 'conf t', 'vlan 999', 'name UNUSED', 'interface range g0/3 - 7', 'switchport mode access', 'switchport access vlan 999', 'shutdown', 'end', 'show interfaces status'],
    'sec-04-lock-a-port': ['en', 'conf t', 'int g0/1', 'switchport mode access', 'switchport port-security', 'switchport port-security maximum 1', 'switchport port-security violation shutdown', 'switchport port-security mac-address sticky', 'end', 'PC-A: ping 192.168.1.20', 'show port-security interface g0/1', 'show running-config'],
    'sec-05-err-disabled-port': ['en', 'show interfaces status', 'show port-security interface g0/1', 'conf t', 'int g0/1', 'no switchport port-security mac-address 0011.22aa.00ff', 'switchport port-security mac-address sticky', 'shutdown', 'no shutdown', 'end', 'PC-A: ping 192.168.1.20'],
    'sec-06-exam-harden-the-switch': ['en', 'conf t', 'hostname Secure-SW1', 'banner motd #Authorized access only#', 'enable secret H4rden!', 'service password-encryption', 'username admin privilege 15 secret Adm1n-Sec', 'line con 0', 'password c0nsole', 'login', 'line vty 0 4', 'login local', 'transport input ssh', 'exit', 'ip domain-name lab.local', 'crypto key generate rsa modulus 2048', 'ip ssh version 2', 'interface range g0/1 - 2', 'switchport mode access', 'switchport port-security', 'switchport port-security mac-address sticky', 'interface range g0/3 - 7', 'shutdown', 'end', 'write memory'],
    'ec-01-lacp-bundle': ['en', 'conf t', 'interface range g0/7 - 8', 'channel-group 1 mode active', 'interface port-channel 1', 'switchport mode trunk', 'end', 'show etherchannel summary', 'PC-A: ping 192.168.10.12'],
    'ec-02-channel-never-forms': ['en', 'show etherchannel summary', 'conf t', 'interface range g0/7 - 8', 'channel-group 1 mode active', 'end', 'show etherchannel summary'],
    'ec-03-pagp-and-static': ['en', 'conf t', 'interface range g0/7 - 8', 'channel-group 1 mode desirable', 'interface port-channel 1', 'switchport mode trunk', 'end', 'show etherchannel summary', 'PC-B: ping 192.168.20.12'],
    'rt-01-meet-the-router': ['en', 'show ip interface brief', 'conf t', 'int g0/0', 'ip address 192.168.1.1 255.255.255.0', 'no shutdown', 'end', 'show ip route', 'ping 192.168.1.10'],
    'rt-02-connect-two-routers': ['en', 'conf t', 'int g0/1', 'ip address 10.0.0.1 255.255.255.252', 'no shutdown', 'end', 'show ip route', 'ping 10.0.0.2'],
    'rt-03-first-static-route': ['PC-A: ping 192.168.2.10', 'en', 'conf t', 'ip route 192.168.2.0 255.255.255.0 10.0.0.2', 'end', 'show ip route', 'PC-A: ping 192.168.2.10'],
    'rt-04-missing-return-route': ['PC-A: tracert 192.168.2.10', 'en', 'show ip route', 'R2: en', 'R2: show ip route', 'R2: conf t', 'R2: ip route 192.168.1.0 255.255.255.0 10.0.0.1', 'PC-A: ping 192.168.2.10'],
    'rt-05-default-route': ['en', 'conf t', 'int g0/1', 'ip address 203.0.113.2 255.255.255.252', 'no shutdown', 'exit', 'ip route 0.0.0.0 0.0.0.0 203.0.113.1', 'end', 'show ip route', 'PC-A: ping 8.8.8.8'],
    'rt-06-router-on-a-stick': ['en', 'conf t', 'int g0/0', 'no shutdown', 'int g0/0.10', 'encapsulation dot1q 10', 'ip address 192.168.10.1 255.255.255.0', 'int g0/0.20', 'encapsulation dot1q 20', 'ip address 192.168.20.1 255.255.255.0', 'end', 'PC-A: ping 192.168.20.10'],
    'rt-07-exam-branch-connectivity': ['en', 'conf t', 'int g0/0', 'ip address 192.168.1.1 255.255.255.0', 'no shut', 'int g0/1', 'ip address 10.0.0.1 255.255.255.252', 'no shut', 'exit', 'ip route 192.168.2.0 255.255.255.0 10.0.0.2', 'end', 'write memory', 'R2: en', 'R2: conf t', 'R2: int g0/0', 'R2: ip address 192.168.2.1 255.255.255.0', 'R2: no shut', 'R2: int g0/1', 'R2: ip address 10.0.0.2 255.255.255.252', 'R2: no shut', 'R2: exit', 'R2: ip route 192.168.1.0 255.255.255.0 10.0.0.1', 'R2: end', 'R2: write memory', 'PC-A: ping 192.168.2.10'],
    'os-01-turn-on-ospf': ['en', 'conf t', 'router ospf 1', 'router-id 1.1.1.1', 'network 192.168.1.0 0.0.0.255 area 0', 'network 10.0.0.0 0.0.0.3 area 0', 'end', 'show ip ospf neighbor', 'show ip route', 'PC-A: ping 192.168.2.10'],
    'os-02-three-routers': ['en', 'conf t', 'router ospf 1', 'router-id 2.2.2.2', 'network 192.168.2.0 0.0.0.255 area 0', 'network 10.0.12.0 0.0.0.3 area 0', 'network 10.0.23.0 0.0.0.3 area 0', 'end', 'show ip ospf neighbor', 'PC-A: ping 192.168.3.10'],
    'os-03-passive-interfaces': ['en', 'conf t', 'router ospf 1', 'passive-interface g0/0', 'end', 'show ip protocols', 'PC-B: ping 192.168.1.10'],
    'os-04-neighbor-never-forms': ['en', 'show ip ospf neighbor', 'show ip ospf interface brief', 'conf t', 'router ospf 1', 'no network 10.0.0.0 0.0.0.3 area 1', 'network 10.0.0.0 0.0.0.3 area 0', 'end', 'PC-A: ping 192.168.2.10'],
    'os-05-default-information-originate': ['en', 'conf t', 'ip route 0.0.0.0 0.0.0.0 203.0.113.1', 'router ospf 1', 'default-information originate', 'end', 'PC-B: ping 8.8.8.8'],
    'os-07-join-a-second-area': ['en', 'conf t', 'router ospf 1', 'router-id 1.1.1.1', 'network 192.168.1.0 0.0.0.255 area 1', 'network 10.0.12.0 0.0.0.3 area 1', 'passive-interface g0/0', 'end', 'show ip ospf neighbor', 'show ip route', 'PC-A: ping 192.168.4.10'],
    'os-08-area-without-a-backbone': ['en', 'show ip ospf neighbor', 'show ip ospf interface brief', 'conf t', 'router ospf 1', 'no network 10.0.23.0 0.0.0.3 area 1', 'network 10.0.23.0 0.0.0.3 area 0', 'no network 2.2.2.2 0.0.0.0 area 1', 'network 2.2.2.2 0.0.0.0 area 0', 'end', 'show ip ospf neighbor', 'PC-A: ping 192.168.4.10'],
    'os-09-exam-multi-area-campus': [
      'en', 'conf t', 'router ospf 1', 'router-id 1.1.1.1', 'network 192.168.1.0 0.0.0.255 area 1', 'network 10.0.12.0 0.0.0.3 area 1', 'passive-interface g0/0', 'end', 'write memory',
      'R2: en', 'R2: conf t', 'R2: router ospf 1', 'R2: router-id 2.2.2.2', 'R2: network 10.0.12.0 0.0.0.3 area 1', 'R2: network 10.0.23.0 0.0.0.3 area 0', 'R2: network 2.2.2.2 0.0.0.0 area 0', 'R2: end', 'R2: write memory',
      'R3: en', 'R3: conf t', 'R3: router ospf 1', 'R3: router-id 3.3.3.3', 'R3: network 10.0.23.0 0.0.0.3 area 0', 'R3: network 10.0.34.0 0.0.0.3 area 2', 'R3: network 3.3.3.3 0.0.0.0 area 0', 'R3: end', 'R3: write memory',
      'R4: en', 'R4: conf t', 'R4: router ospf 1', 'R4: router-id 4.4.4.4', 'R4: network 10.0.34.0 0.0.0.3 area 2', 'R4: network 192.168.4.0 0.0.0.255 area 2', 'R4: passive-interface g0/1', 'R4: end', 'R4: write memory',
      'PC-A: ping 192.168.4.10', 'PC-D: ping 192.168.1.10',
    ],
    'stp-01-find-the-root': ['en', 'show spanning-tree vlan 10', 'show spanning-tree', 'SW2: en', 'SW2: show spanning-tree vlan 10', 'SW3: en', 'SW3: show spanning-tree vlan 10'],
    'stp-02-choose-the-root': ['en', 'conf t', 'spanning-tree vlan 1,10,20 root primary', 'end', 'SW2: en', 'SW2: conf t', 'SW2: spanning-tree vlan 1,10,20 root secondary', 'SW2: end', 'show spanning-tree vlan 10', 'PC-A: ping 192.168.10.12'],
    'stp-03-portfast-bpduguard': ['en', 'conf t', 'int g0/1', 'spanning-tree portfast', 'spanning-tree bpduguard enable', 'exit', 'spanning-tree mode rapid-pvst', 'end', 'show spanning-tree vlan 10'],
    'stp-04-err-disabled-uplink': ['en', 'show interfaces status', 'show spanning-tree vlan 10', 'conf t', 'int g0/8', 'no spanning-tree bpduguard', 'shutdown', 'no shutdown', 'end', 'show spanning-tree vlan 10', 'PC-A: ping 192.168.10.12'],
    'stp-05-exam-design-the-tree': [
      'en', 'conf t', 'spanning-tree mode rapid-pvst', 'spanning-tree vlan 1,10 root primary', 'spanning-tree vlan 20 root secondary', 'int g0/1', 'spanning-tree portfast', 'spanning-tree bpduguard enable', 'end', 'write memory',
      'SW2: en', 'SW2: conf t', 'SW2: spanning-tree mode rapid-pvst', 'SW2: spanning-tree vlan 20 root primary', 'SW2: spanning-tree vlan 1,10 root secondary', 'SW2: int g0/1', 'SW2: spanning-tree portfast', 'SW2: spanning-tree bpduguard enable', 'SW2: end', 'SW2: write memory',
      'SW3: en', 'SW3: conf t', 'SW3: spanning-tree mode rapid-pvst', 'SW3: int g0/1', 'SW3: spanning-tree portfast', 'SW3: spanning-tree bpduguard enable', 'SW3: end', 'SW3: write memory',
      'PC-A: ping 192.168.10.12', 'PC-B: ping 192.168.20.1',
    ],
    'os-06-exam-ospf-campus': [
      'en', 'conf t', 'router ospf 1', 'router-id 1.1.1.1', 'network 192.168.1.0 0.0.0.255 area 0', 'network 10.0.12.0 0.0.0.3 area 0', 'passive-interface g0/0', 'end', 'write memory',
      'R2: en', 'R2: conf t', 'R2: router ospf 1', 'R2: router-id 2.2.2.2', 'R2: network 192.168.2.0 0.0.0.255 area 0', 'R2: network 10.0.12.0 0.0.0.3 area 0', 'R2: network 10.0.23.0 0.0.0.3 area 0', 'R2: passive-interface g0/0', 'R2: end', 'R2: write memory',
      'R3: en', 'R3: conf t', 'R3: router ospf 1', 'R3: router-id 3.3.3.3', 'R3: network 192.168.3.0 0.0.0.255 area 0', 'R3: network 10.0.23.0 0.0.0.3 area 0', 'R3: passive-interface g0/0', 'R3: end', 'R3: write memory',
      'PC-A: ping 192.168.3.10', 'PC-B: ping 192.168.3.10',
    ],
    'ex-01-two-switch-vlan-campus': [
      ...['SW1', 'SW2'].flatMap((d, i) => [`${d}: en`, `${d}: conf t`, `${d}: vlan 10`, `${d}: name SALES`, `${d}: vlan 20`, `${d}: name HR`, `${d}: vlan 99`, `${d}: name MGMT`, `${d}: int g0/1`, `${d}: switchport mode access`, `${d}: switchport access vlan 10`, `${d}: int g0/2`, `${d}: switchport mode access`, `${d}: switchport access vlan 20`, `${d}: int g0/8`, `${d}: switchport mode trunk`, `${d}: switchport trunk allowed vlan 10,20,99`, `${d}: switchport trunk native vlan 99`, `${d}: int vlan 99`, `${d}: ip address 10.0.99.${i + 1} 255.255.255.0`, `${d}: no shutdown`, `${d}: end`, `${d}: write memory`]),
      'PC-A: ping 192.168.10.12', 'PC-B: ping 192.168.20.12', 'SW1: ping 10.0.99.2',
    ],
    'ex-02-static-routing-three-sites': [
      'en', 'conf t', 'ip route 192.168.2.0 255.255.255.0 10.0.12.2', 'ip route 192.168.3.0 255.255.255.0 10.0.12.2', 'end', 'write memory',
      'R2: en', 'R2: conf t', 'R2: ip route 192.168.1.0 255.255.255.0 10.0.12.1', 'R2: ip route 192.168.3.0 255.255.255.0 10.0.23.2', 'R2: end', 'R2: write memory',
      'R3: en', 'R3: conf t', 'R3: ip route 192.168.1.0 255.255.255.0 10.0.23.1', 'R3: ip route 192.168.2.0 255.255.255.0 10.0.23.1', 'R3: end', 'R3: write memory',
      'PC-A: ping 192.168.3.10', 'PC-C: ping 192.168.2.10', 'PC-B: ping 192.168.1.10',
    ],
    'ex-03-intervlan-routing-ospf': ['en', 'conf t', 'int g0/0', 'no shutdown', 'int g0/0.10', 'encapsulation dot1q 10', 'ip address 192.168.10.1 255.255.255.0', 'int g0/0.20', 'encapsulation dot1q 20', 'ip address 192.168.20.1 255.255.255.0', 'int g0/1', 'ip address 10.0.0.1 255.255.255.252', 'no shutdown', 'router ospf 1', 'router-id 1.1.1.1', 'network 192.168.10.0 0.0.0.255 area 0', 'network 192.168.20.0 0.0.0.255 area 0', 'network 10.0.0.0 0.0.0.3 area 0', 'end', 'write memory', 'PC-A: ping 192.168.30.10', 'PC-B: ping 192.168.10.10'],
    'ex-04-troubleshooting-marathon': ['en', 'show vlan brief', 'conf t', 'int g0/1', 'switchport access vlan 10', 'int g0/8', 'switchport trunk allowed vlan 10,20', 'end', 'R1: en', 'R1: show ip interface brief', 'R1: conf t', 'R1: int g0/1', 'R1: no shutdown', 'R1: end', 'R2: en', 'R2: show ip protocols', 'R2: conf t', 'R2: router ospf 1', 'R2: network 192.168.30.0 0.0.0.255 area 0', 'R2: end', 'PC-A: ping 192.168.20.10', 'PC-A: ping 192.168.30.10', 'PC-C: ping 192.168.20.10'],
    'ex-05-secure-branch': [
      'en', 'conf t', 'enable secret Sw1tch!', 'ip domain-name lab.local', 'crypto key generate rsa modulus 2048', 'ip ssh version 2', 'username admin privilege 15 secret Adm1n-Sw', 'line vty 0 4', 'login local', 'transport input ssh', 'exit', 'interface range g0/3 - 7', 'shutdown', 'end', 'write memory',
      'R1: en', 'R1: conf t', 'R1: enable secret R0uter!', 'R1: banner motd #Authorized access only#', 'R1: service password-encryption', 'R1: ip domain-name lab.local', 'R1: crypto key generate rsa modulus 2048', 'R1: ip ssh version 2', 'R1: username admin privilege 15 secret Adm1n-Rt', 'R1: line vty 0 4', 'R1: login local', 'R1: transport input ssh', 'R1: end', 'R1: write memory',
      'PC-A: ping 192.168.1.1',
    ],
    'ex-06-final-capstone': [
      'en', 'conf t', 'vlan 10', 'name SALES', 'vlan 20', 'name HR', 'int g0/1', 'switchport mode access', 'switchport access vlan 10', 'int g0/2', 'switchport mode access', 'switchport access vlan 20', 'int g0/8', 'switchport mode trunk', 'exit', 'enable secret Capst0ne!', 'end', 'write memory',
      'R1: en', 'R1: conf t', 'R1: int g0/0', 'R1: no shutdown', 'R1: int g0/0.10', 'R1: encapsulation dot1q 10', 'R1: ip address 192.168.10.1 255.255.255.0', 'R1: int g0/0.20', 'R1: encapsulation dot1q 20', 'R1: ip address 192.168.20.1 255.255.255.0', 'R1: int g0/1', 'R1: ip address 10.0.0.1 255.255.255.252', 'R1: no shutdown', 'R1: router ospf 1', 'R1: router-id 1.1.1.1', 'R1: network 192.168.10.0 0.0.0.255 area 0', 'R1: network 192.168.20.0 0.0.0.255 area 0', 'R1: network 10.0.0.0 0.0.0.3 area 0', 'R1: exit', 'R1: enable secret Capst0ne!', 'R1: end', 'R1: write memory',
      'R2: en', 'R2: conf t', 'R2: int g0/1', 'R2: ip address 10.0.0.2 255.255.255.252', 'R2: no shutdown', 'R2: int g0/0', 'R2: ip address 203.0.113.2 255.255.255.252', 'R2: no shutdown', 'R2: exit', 'R2: ip route 0.0.0.0 0.0.0.0 203.0.113.1', 'R2: router ospf 1', 'R2: router-id 2.2.2.2', 'R2: network 10.0.0.0 0.0.0.3 area 0', 'R2: default-information originate', 'R2: exit', 'R2: enable secret Capst0ne!', 'R2: end', 'R2: write memory',
      'PC-A: ping 192.168.20.10', 'PC-A: ping 8.8.8.8', 'PC-B: ping 8.8.8.8',
    ],
    'acl-01-first-standard-acl': ['en', 'conf t', 'access-list 10 deny 192.168.20.0 0.0.0.255', 'access-list 10 permit any', 'int g0/1', 'ip access-group 10 out', 'end', 'PC-B: ping 10.10.10.10', 'PC-A: ping 10.10.10.10', 'show access-lists'],
    'acl-02-extended-named-acl': ['en', 'conf t', 'ip access-list extended NO-PING-SRV', 'deny icmp 192.168.10.0 0.0.0.255 host 10.10.10.10 echo', 'permit ip any any', 'int g0/0.10', 'ip access-group NO-PING-SRV in', 'end', 'PC-A: ping 10.10.10.10', 'PC-A: ping 192.168.20.10', 'PC-B: ping 10.10.10.10'],
    'acl-03-implicit-deny': ['en', 'show access-lists', 'conf t', 'ip access-list extended SERVER-POLICY', 'permit ip any any', 'end', 'PC-B: ping 192.168.10.10', 'PC-B: ping 10.10.10.10'],
    'acl-04-protect-vty': ['en', 'conf t', 'access-list 5 remark Admin PC only', 'access-list 5 permit host 192.168.10.10', 'line vty 0 4', 'access-class 5 in', 'end', 'show running-config'],
    'acl-05-exam-access-policy': ['en', 'conf t', 'ip access-list extended HR-POLICY', 'deny ip 192.168.20.0 0.0.0.255 host 10.10.10.10', 'permit ip any any', 'ip access-list extended SALES-POLICY', 'permit tcp 192.168.10.0 0.0.0.255 host 10.10.10.10 eq 80', 'permit icmp 192.168.10.0 0.0.0.255 host 10.10.10.10', 'deny ip 192.168.10.0 0.0.0.255 host 10.10.10.10', 'permit ip any any', 'exit', 'access-list 5 permit host 192.168.10.10', 'int g0/0.20', 'ip access-group HR-POLICY in', 'int g0/0.10', 'ip access-group SALES-POLICY in', 'line vty 0 4', 'access-class 5 in', 'end', 'write memory', 'PC-B: ping 10.10.10.10', 'PC-B: ping 192.168.10.10', 'PC-A: ping 10.10.10.10', 'PC-A: ping 192.168.20.10'],
    'dh-01-dhcp-server': ['PC-A: ipconfig /renew', 'en', 'conf t', 'ip dhcp excluded-address 192.168.10.1 192.168.10.9', 'ip dhcp pool SALES', 'network 192.168.10.0 255.255.255.0', 'default-router 192.168.10.1', 'dns-server 8.8.8.8', 'end', 'PC-A: ipconfig /renew', 'PC-A: ping 192.168.10.1', 'show ip dhcp binding'],
    'dh-02-bindings-and-pool': ['PC-A: ipconfig /renew', 'PC-B: ipconfig /renew', 'en', 'show ip dhcp binding', 'show ip dhcp pool', 'PC-A: ping 192.168.10.11'],
    'dh-03-dhcp-relay': ['PC-A: ipconfig /renew', 'en', 'conf t', 'int g0/0', 'ip helper-address 10.0.0.2', 'end', 'PC-A: ipconfig /renew', 'PC-A: ping 10.0.0.2'],
    'dh-04-wrong-gateway': ['PC-A: ipconfig /all', 'en', 'conf t', 'ip dhcp pool SALES', 'default-router 192.168.10.1', 'end', 'PC-A: ipconfig /renew', 'PC-A: ping 10.0.0.2'],
    'ex-07-services-and-security': [
      'en', 'conf t', 'ip dhcp excluded-address 192.168.10.1 192.168.10.9', 'ip dhcp excluded-address 192.168.20.1 192.168.20.9', 'ip dhcp pool SALES', 'network 192.168.10.0 255.255.255.0', 'default-router 192.168.10.1', 'dns-server 10.10.10.10', 'ip dhcp pool HR', 'network 192.168.20.0 255.255.255.0', 'default-router 192.168.20.1', 'dns-server 10.10.10.10', 'exit',
      'ip access-list extended HR-POLICY', 'permit udp 192.168.20.0 0.0.0.255 host 10.10.10.10 eq 53', 'deny ip 192.168.20.0 0.0.0.255 host 10.10.10.10', 'permit ip any any', 'int g0/0.20', 'ip access-group HR-POLICY in', 'exit', 'access-list 5 permit host 192.168.10.10', 'line vty 0 4', 'access-class 5 in', 'end', 'write memory',
      'PC-A: ipconfig /renew', 'PC-B: ipconfig /renew', 'PC-A: ping 10.10.10.10', 'PC-A: ping 192.168.20.10', 'PC-B: ping 192.168.10.10', 'PC-B: ping 10.10.10.10',
    ],
    'nat-01-static-nat': ['NET-PC: ping 203.0.113.10', 'en', 'conf t', 'ip nat inside source static 192.168.10.20 203.0.113.10', 'int g0/0', 'ip nat inside', 'int g0/1', 'ip nat outside', 'end', 'NET-PC: ping 203.0.113.10', 'show ip nat translations'],
    'nat-02-pat-overload': ['PC-A: ping 8.8.8.8', 'en', 'conf t', 'access-list 1 permit 192.168.10.0 0.0.0.255', 'ip nat inside source list 1 interface g0/1 overload', 'int g0/0', 'ip nat inside', 'int g0/1', 'ip nat outside', 'end', 'PC-A: ping 8.8.8.8', 'PC-B: ping 8.8.8.8', 'show ip nat translations'],
    'nat-03-dynamic-pool': ['en', 'conf t', 'ip nat pool PUBLIC 203.0.113.20 203.0.113.21 netmask 255.255.255.0', 'access-list 1 permit 192.168.10.0 0.0.0.255', 'ip nat inside source list 1 pool PUBLIC', 'end', 'PC-A: ping 8.8.8.8', 'PC-B: ping 8.8.8.8', 'SRV1: ping 8.8.8.8', 'conf t', 'ip nat inside source list 1 pool PUBLIC overload', 'end', 'SRV1: ping 8.8.8.8'],
    'nat-04-exam-internet-edge': ['en', 'conf t', 'ip nat inside source static 192.168.10.20 203.0.113.10', 'access-list 1 permit 192.168.10.0 0.0.0.255', 'ip nat inside source list 1 interface g0/1 overload', 'int g0/0', 'ip nat inside', 'int g0/1', 'ip nat outside', 'end', 'write memory', 'NET-PC: ping 203.0.113.10', 'PC-A: ping 8.8.8.8', 'PC-B: ping 8.8.8.8'],
    'v6-01-first-addresses': ['en', 'conf t', 'ipv6 unicast-routing', 'int g0/0', 'ipv6 address 2001:db8:1::1/64', 'no shutdown', 'end', 'show ipv6 interface brief', 'ping 2001:db8:1::10'],
    'v6-02-eui64-link-local': ['en', 'conf t', 'int g0/1', 'ipv6 address 2001:db8:12::/64 eui-64', 'ipv6 address fe80::1 link-local', 'no shutdown', 'end', 'show ipv6 interface brief', 'ping 2001:db8:12::2'],
    'v6-03-static-routes': ['PC-A: ping 2001:db8:2::10', 'en', 'conf t', 'ipv6 route 2001:db8:2::/64 2001:db8:12::2', 'end', 'show ipv6 route', 'PC-A: ping 2001:db8:2::10'],
    'v6-04-default-via-link-local': ['en', 'conf t', 'ipv6 route ::/0 fe80::2', 'ipv6 route ::/0 g0/1 fe80::2', 'end', 'show ipv6 route', 'PC-A: ping 2001:db8:ffff::1'],
    'v6-05-exam-dual-stack': [
      'en', 'conf t', 'ipv6 unicast-routing', 'int g0/0', 'ipv6 address 2001:db8:1::1/64', 'int g0/1', 'ipv6 address 2001:db8:12::1/64', 'exit', 'ipv6 route 2001:db8:2::/64 2001:db8:12::2', 'end', 'write memory',
      'R2: en', 'R2: conf t', 'R2: ipv6 unicast-routing', 'R2: int g0/0', 'R2: ipv6 address 2001:db8:2::1/64', 'R2: int g0/1', 'R2: ipv6 address 2001:db8:12::2/64', 'R2: exit', 'R2: ipv6 route 2001:db8:1::/64 2001:db8:12::1', 'R2: end', 'R2: write memory',
      'PC-A: ping 2001:db8:2::10', 'PC-B: ping 2001:db8:1::10', 'PC-A: ping 192.168.2.10',
    ],
  };

  const GET_IFS = 'PC-A: curl -k -u netops:Aut0mate! https://192.168.1.1/restconf/data/ietf-interfaces:interfaces';
  const PATCH_G00 = `PC-A: curl -k -i -u netops:Aut0mate! -X PATCH -H 'Content-Type: application/yang-data+json' -d '{"ietf-interfaces:interface": {"name": "GigabitEthernet0/0", "description": "Sales LAN"}}' https://192.168.1.1/restconf/data/ietf-interfaces:interfaces/interface=GigabitEthernet0%2F0`;
  Object.assign(solutions, {
    'ns-01-password-policy': ['en', 'conf t', 'security passwords min-length 10', 'enable secret cisco', 'enable secret Edge-R1-S3cret', 'login block-for 120 attempts 3 within 60', 'line con 0', 'exec-timeout 5 0', 'line vty 0 4', 'exec-timeout 5 0', 'exit', 'service password-encryption', 'end', 'show login'],
    'ns-02-aaa-local': ['enable', 'Edge-R1-S3cret', 'conf t', 'aaa new-model', 'aaa authentication login default local', 'username netops privilege 15 secret Aut0mate-Edge', 'ip domain-name lab.local', 'crypto key generate rsa modulus 2048', 'ip ssh version 2', 'line vty 0 4', 'transport input ssh', 'end', 'write memory'],
    'ns-03-dhcp-snooping': ['PC-A: ipconfig /renew', 'en', 'conf t', 'ip dhcp snooping', 'ip dhcp snooping vlan 10', 'no ip dhcp snooping information option', 'end', 'PC-A: ipconfig /renew', 'conf t', 'int g0/8', 'ip dhcp snooping trust', 'end', 'PC-A: ipconfig /renew', 'show ip dhcp snooping', 'show ip dhcp snooping binding'],
    'ns-04-dynamic-arp-inspection': ['en', 'conf t', 'ip arp inspection vlan 10', 'int g0/8', 'ip arp inspection trust', 'end', 'PC-A: ping 192.168.10.1', 'show ip arp inspection vlan 10', 'show ip arp inspection interfaces'],
    'ns-05-dai-static-server': ['SRV1: ping 192.168.10.1', 'en', 'show ip arp inspection interfaces', 'conf t', 'int g0/3', 'ip arp inspection trust', 'end', 'SRV1: ping 192.168.10.1', 'PC-A: ping 192.168.10.1'],
    'ns-06-exam-harden-the-branch': [
      'en', 'conf t', 'security passwords min-length 10', 'enable secret Br4nch-Secret', 'login block-for 120 attempts 3 within 60', 'aaa new-model', 'aaa authentication login default local', 'username netops privilege 15 secret Aut0mate-Edge', 'ip domain-name lab.local', 'crypto key generate rsa modulus 2048', 'ip ssh version 2', 'access-list 5 permit host 192.168.10.50', 'line vty 0 4', 'transport input ssh', 'access-class 5 in', 'exec-timeout 5 0', 'line con 0', 'exec-timeout 5 0', 'exit', 'service password-encryption', 'end', 'write memory',
      'SW1: en', 'SW1: conf t', 'SW1: ip dhcp snooping', 'SW1: ip dhcp snooping vlan 10', 'SW1: no ip dhcp snooping information option', 'SW1: ip arp inspection vlan 10', 'SW1: int g0/8', 'SW1: ip dhcp snooping trust', 'SW1: ip arp inspection trust', 'SW1: int g0/3', 'SW1: ip arp inspection trust', 'SW1: interface range g0/1 - 2', 'SW1: switchport port-security', 'SW1: switchport port-security maximum 1', 'SW1: switchport port-security mac-address sticky', 'SW1: end',
      'PC-A: ipconfig /renew', 'PC-A: ping 192.168.10.50', 'SRV1: ping 192.168.10.1', 'SW1: write memory',
    ],
    'au-01-enable-the-api': [GET_IFS, 'en', 'conf t', 'username netops privilege 15 secret Aut0mate!', 'ip http secure-server', 'ip http authentication local', 'restconf', 'ip domain-name lab.local', 'crypto key generate rsa modulus 2048', 'netconf-yang', 'end', 'show platform software yang-management process', GET_IFS],
    'au-02-read-the-device-as-json': ['PC-A: curl -k -u netops:Aut0mate! https://192.168.1.1/restconf/data/ietf-interfaces:interfaces/interface=GigabitEthernet0%2F1', 'PC-A: curl -k -u netops:Aut0mate! https://192.168.1.1/restconf/data/Cisco-IOS-XE-native:native/hostname', 'en', 'conf t', 'int g0/1', 'no shutdown', 'end', 'ping 10.0.0.2'],
    'au-03-configure-through-the-api': [PATCH_G00, `PC-A: curl -k -i -u netops:Aut0mate! -X PATCH -H 'Content-Type: application/yang-data+json' -d '{"Cisco-IOS-XE-native:hostname": "Branch-R1"}' https://192.168.1.1/restconf/data/Cisco-IOS-XE-native:native/hostname`, 'en', 'show running-config'],
    'au-04-deploy-from-a-json-intent': ['en', 'conf t', 'hostname Site2-R2', 'int g0/0', 'description Site 2 LAN', 'ip address 192.168.2.1 255.255.255.0', 'no shutdown', 'int g0/1', 'description Link to R1', 'ip address 10.0.0.2 255.255.255.252', 'no shutdown', 'exit', 'ip route 192.168.1.0 255.255.255.0 10.0.0.1', 'ntp server 192.168.2.50', 'end', 'SRV1: ping 192.168.1.10'],
    'au-05-telemetry-for-the-assistant': ['en', 'conf t', 'logging host 192.168.2.50', 'logging trap informational', 'snmp-server community NetOps-RO ro', 'snmp-server location Branch 1 comms room', 'snmp-server contact netops@example.com', 'ntp server 192.168.2.50', 'end', 'show logging', 'show ntp status'],
    'au-06-review-the-ai-change': ['PC-B: ping 192.168.2.50', 'PC-A: ping 192.168.2.50', 'en', 'conf t', 'ip access-list extended GUEST-POLICY', 'deny ip 192.168.3.0 0.0.0.255 host 192.168.2.50', 'permit ip any any', 'int g0/2', 'ip access-group GUEST-POLICY in', 'end', 'PC-B: ping 192.168.2.50', 'PC-A: ping 192.168.2.50', 'PC-B: ping 10.0.0.2'],
    'au-07-exam-automation-ready-branch': ['en', 'conf t', 'username netops privilege 15 secret Aut0mate!', 'ip http secure-server', 'ip http authentication local', 'restconf', 'ip domain-name lab.local', 'crypto key generate rsa modulus 2048', 'ip ssh version 2', 'netconf-yang', 'logging host 192.168.2.50', 'logging trap informational', 'snmp-server community NetOps-RO ro', 'ntp server 192.168.2.50', 'end', GET_IFS, PATCH_G00, 'write memory'],
  });

  const HEREDOC = (name: string, ...body: string[]) => [`cat > ${name} << 'EOF'`, ...body, 'EOF'];
  Object.assign(solutions, {
    'lx-01-find-your-way': ['pwd', 'ls -la', 'cd /var/log', 'ls', 'cat /etc/os-release', 'man ls', 'cd'],
    'lx-02-make-files-and-folders': ['mkdir -p ~/projects/netlab/docs', 'echo "NetLab project" > ~/projects/netlab/README.md', 'cp ~/projects/netlab/README.md ~/projects/netlab/docs/', 'mv ~/projects/netlab/docs/README.md ~/projects/netlab/docs/intro.md', 'rm ~/old-draft.txt'],
    'lx-03-read-and-search': ['head -3 /var/log/auth.log', 'tail -2 /var/log/auth.log', 'grep -c "Failed password" /var/log/auth.log', 'grep "Failed password" /var/log/auth.log > ~/failed.txt', 'wc -l ~/failed.txt'],
    'lx-04-permissions': ['ls -l', 'chmod 600 secret.txt', 'chmod +x deploy.sh', './deploy.sh', 'mkdir shared', 'chmod 770 shared', 'sudo chown :devops shared'],
    'lx-05-links-and-find': ['ln -s /var/log/app.log ~/app.log', 'ls -l ~/app.log', 'grep ERROR ~/app.log', 'find /var/log -name "*.log"', 'find ~ -type d'],
    'lx-06-exam-shell-essentials': ['mkdir -p ~/reports/2026', 'grep ERROR /var/log/app.log > ~/reports/2026/errors.txt', 'grep -c ERROR /var/log/app.log > ~/reports/2026/count.txt', 'chmod 640 ~/reports/2026/errors.txt', 'ln -s reports/2026/errors.txt ~/latest-errors', 'rm ~/old-draft.txt'],
    'lx-07-become-root': ['cat /etc/shadow', 'sudo -i', 'whoami', 'cat /etc/shadow', 'exit', 'sudo apt update'],
    'lx-08-users-and-groups': ['sudo groupadd devops', 'sudo useradd -m -s /bin/bash -G devops alice', 'sudo passwd alice', 'Al1ce-pass', 'Al1ce-pass', 'sudo usermod -aG devops bob', 'id alice', 'cat /etc/group'],
    'lx-09-run-a-web-server': ['systemctl status nginx', 'sudo systemctl enable --now nginx', 'ss -tlnp', 'echo "<h1>Welcome to NetLab on web1</h1>" | sudo tee /var/www/html/index.html', 'PC-A: curl http://192.168.1.50'],
    'lx-10-processes-and-logs': ['ps aux | grep runaway', 'pkill -f runaway', 'ps aux | grep runaway', 'journalctl -u ssh', 'grep -c ERROR /var/log/app.log'],
    'lx-11-network-from-the-host': ['ip addr', 'ip route', 'ping -c 3 192.168.1.1', 'ping -c 3 192.168.2.50', 'curl -s -k -u netops:Aut0mate! https://192.168.1.1/restconf/data/ietf-interfaces:interfaces'],
    'lx-12-exam-bring-up-the-server': ['sudo hostnamectl set-hostname branch-web1', 'sudo groupadd webteam', 'sudo useradd -m -s /bin/bash -G webteam carol', 'sudo passwd carol', 'C4rol-pass', 'C4rol-pass', 'sudo apt install -y nginx', 'sudo systemctl enable --now nginx', 'echo "<h1>Branch web1</h1>" | sudo tee /var/www/html/index.html', 'pkill -f runaway', 'ping -c 2 192.168.1.1', 'PC-A: curl http://192.168.1.50'],
    'lx-13-variables-and-quotes': ['site=netlab', 'echo "Site: $site"', "echo 'Literal: $site'", 'today=$(date +%F)', 'echo $today', 'export EDITOR=nano', 'env | grep EDITOR', 'echo $((7*6))'],
    'lx-14-your-first-script': [...HEREDOC('hello.sh', '#!/bin/bash', 'echo "Hello, $1!"'), 'cat hello.sh', 'chmod +x hello.sh', './hello.sh NetLab'],
    'lx-15-conditions-and-exit-codes': [...HEREDOC('check.sh', '#!/bin/bash', 'if [ -f "$1" ]; then', '  echo "$1 exists"', 'else', '  echo "$1 missing"', '  exit 1', 'fi'), 'chmod +x check.sh', './check.sh /etc/hosts', './check.sh /etc/nothing; echo $?'],
    'lx-16-loops': ['for f in /var/log/*.log; do echo "$f: $(wc -l < $f) lines"; done', 'while read t; do mkdir -p ~/teams/$t; done < teams.txt', 'ls ~/teams'],
    'lx-17-functions': [...HEREDOC('lib.sh', 'log() {', '  echo "[$(date +%T)] $*"', '}', 'check_service() {', '  systemctl is-active "$1" > /dev/null && return 0', '  return 1', '}'), 'source lib.sh', 'log hello', 'check_service ssh && echo "ssh is up"'],
    'lx-18-text-pipelines': ["grep \"Failed password\" /var/log/auth.log | awk '{print $(NF-3)}' | sort | uniq -c | sort -rn > ~/attackers.txt", 'cat ~/attackers.txt', 'cut -d: -f1,7 /etc/passwd | grep bash', "sed 's/ERROR/ERR/' /var/log/app.log | head -3"],
    'lx-19-exam-backup-script': [...HEREDOC('backup.sh', '#!/bin/bash', 'if [ -z "$1" ]; then', '  echo "usage: backup.sh <dir>"', '  exit 1', 'fi', 'dest=~/backup-$(date +%F)', 'mkdir -p "$dest"', 'count=0', 'for f in "$1"/*; do', '  cp "$f" "$dest/"', '  count=$((count+1))', 'done', 'echo "Backed up $count files to $dest"'), 'chmod +x backup.sh', './backup.sh', './backup.sh ~/docs'],
    'lx-20-hello-python': ['python3 --version', "python3 -c 'print(\"Hello from Python\")'", ...HEREDOC('hello.py', 'name = "NetLab"', 'print(f"Hello, {name}!")'), 'python3 hello.py'],
    'lx-21-read-files-with-python': [...HEREDOC('errors.py', 'errors = []', 'with open("/var/log/app.log") as f:', '    for line in f:', '        if "ERROR" in line:', '            errors.append(line.rstrip())', 'print(f"{len(errors)} errors")', 'with open("summary.txt", "w") as out:', '    out.write("\\n".join(errors) + "\\n")'), 'python3 errors.py', 'cat summary.txt'],
    'lx-22-read-json-with-python': ['cat intent.json', ...HEREDOC('intent.py', 'import json', 'with open("intent.json") as f:', '    intent = json.load(f)', 'print(intent["device"]["hostname"])', 'for iface in intent["interfaces"]:', '    print(iface["name"], iface["ipv4"]["ip"])'), 'python3 intent.py'],
    'lx-23-generate-config-from-json': [...HEREDOC('render.py', 'import json', 'intent = json.load(open("intent.json"))', 'lines = [f"hostname {intent[\'device\'][\'hostname\']}"]', 'for i in intent["interfaces"]:', '    lines += [f"interface {i[\'name\']}", f" description {i[\'description\']}", f" ip address {i[\'ipv4\'][\'ip\']} {i[\'ipv4\'][\'netmask\']}", " no shutdown"]', 'for r in intent["static-routes"]:', '    lines.append(f"ip route {r[\'prefix\']} {r[\'netmask\']} {r[\'next-hop\']}")', 'for s in intent["ntp"]["servers"]:', '    lines.append(f"ntp server {s}")', 'open("r2.cfg", "w").write("\\n".join(lines) + "\\n")'), 'python3 render.py', 'cat r2.cfg'],
    'lx-24-exam-audit-the-server': [...HEREDOC('audit.py', 'import json', 'users = []', 'for line in open("/etc/passwd"):', '    name, _, uid, _, _, _, shell = line.rstrip().split(":")', '    if int(uid) >= 1000 and "nologin" not in shell:', '        users.append((name, uid, shell))', 'with open("users.csv", "w") as f:', '    for u in users:', '        f.write(",".join(u) + "\\n")', 'failed = sum(1 for l in open("/var/log/auth.log") if "Failed password" in l)', 'print(f"{failed} failed logins")', 'json.dump({"users": [u[0] for u in users], "failed_logins": failed}, open("audit.json", "w"), indent=2)'), 'python3 audit.py', 'cat users.csv'],
  });

  const TEE = (file: string, ...body: string[]) => [`sudo tee ${file} << 'EOF'`, ...body, 'EOF'];
  const NETLAB_TLS = ['server {', '    listen 80;', '    server_name netlab.lab.local;', '    return 301 https://$host$request_uri;', '}', 'server {', '    listen 443 ssl;', '    server_name netlab.lab.local;', '    ssl_certificate /etc/ssl/certs/netlab.crt;', '    ssl_certificate_key /etc/ssl/private/netlab.key;', '    add_header Strict-Transport-Security "max-age=31536000" always;', '    root /var/www/netlab;', '    index index.html;', '}'];
  Object.assign(solutions, {
    'lx-25-serve-a-site-with-nginx': ['cat /etc/nginx/nginx.conf', 'ls -l /etc/nginx/sites-enabled', 'sudo mkdir -p /var/www/netlab', 'echo "<h1>NetLab site</h1>" | sudo tee /var/www/netlab/index.html', ...TEE('/etc/nginx/sites-available/netlab.conf', 'server {', '    listen 80;', '    server_name netlab.lab.local;', '    root /var/www/netlab;', '    index index.html;', '}'), 'sudo ln -s /etc/nginx/sites-available/netlab.conf /etc/nginx/sites-enabled/', 'sudo nginx -t', 'sudo systemctl enable --now nginx', 'curl -H "Host: netlab.lab.local" http://192.168.1.50', 'PC-A: curl -H "Host: netlab.lab.local" http://192.168.1.50'],
    'lx-26-virtual-hosts': ['sudo mkdir -p /var/www/shop', "echo '<h1>Shop</h1>' | sudo tee /var/www/shop/index.html", ...TEE('/etc/nginx/conf.d/shop.conf', 'server {', '    listen 80;', '    server_name shop.lab.local;', '    root /var/www/shop;', '    index index.html;', '}'), 'sudo nginx -t', 'sudo systemctl reload nginx', 'echo "127.0.0.1 netlab.lab.local shop.lab.local" | sudo tee -a /etc/hosts', 'curl http://shop.lab.local', 'curl http://netlab.lab.local', 'curl -H "Host: nobody.example" http://192.168.1.50'],
    'lx-27-troubleshoot-nginx-config': ['sudo systemctl start nginx', 'sudo nginx -t', "sudo sed -i 's/servr_name/server_name/' /etc/nginx/conf.d/netlab.conf", "sudo sed -i 's#root /var/www/netlab$#root /var/www/netlab;#' /etc/nginx/conf.d/netlab.conf", 'sudo nginx -t', 'sudo systemctl start nginx', 'curl -H "Host: netlab.lab.local" http://192.168.1.50'],
    'lx-28-self-signed-tls': ['sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/netlab.key -out /etc/ssl/certs/netlab.crt -subj "/CN=netlab.lab.local"', 'sudo chmod 600 /etc/ssl/private/netlab.key', 'sudo openssl x509 -in /etc/ssl/certs/netlab.crt -noout -subject -dates', ...TEE('/etc/nginx/conf.d/netlab.conf', 'server {', '    listen 80;', '    listen 443 ssl;', '    server_name netlab.lab.local;', '    ssl_certificate /etc/ssl/certs/netlab.crt;', '    ssl_certificate_key /etc/ssl/private/netlab.key;', '    root /var/www/netlab;', '    index index.html;', '}'), 'sudo nginx -t', 'sudo systemctl reload nginx', 'curl -H "Host: netlab.lab.local" https://192.168.1.50', 'curl -k -H "Host: netlab.lab.local" https://192.168.1.50'],
    'lx-29-redirect-http-to-https': [...TEE('/etc/nginx/conf.d/netlab.conf', ...NETLAB_TLS), 'sudo nginx -t', 'sudo systemctl reload nginx', 'curl -I http://netlab.lab.local', 'curl -kLi http://netlab.lab.local'],
    'lx-30-reverse-proxy': ['curl http://192.168.2.50:8080', ...TEE('/etc/nginx/conf.d/netlab.conf', 'server {', '    listen 80;', '    server_name netlab.lab.local;', '    root /var/www/netlab;', '    index index.html;', '    location /app/ {', '        proxy_pass http://192.168.2.50:8080/;', '        proxy_set_header Host $host;', '    }', '}'), 'sudo nginx -t', 'sudo systemctl reload nginx', 'curl http://netlab.lab.local/app/', 'PC-A: curl -H "Host: netlab.lab.local" http://192.168.1.50/app/'],
    'lx-31-load-balancing': [...TEE('/etc/nginx/conf.d/netlab.conf', 'upstream backend {', '    server 192.168.2.50:8080;', '    server 192.168.2.51:8080;', '}', 'server {', '    listen 80;', '    server_name netlab.lab.local;', '    root /var/www/netlab;', '    index index.html;', '    location /app/ {', '        proxy_pass http://backend/;', '        proxy_set_header Host $host;', '    }', '}'), 'sudo nginx -t', 'sudo systemctl reload nginx', 'for i in 1 2 3 4; do curl -s http://netlab.lab.local/app/; done'],
    'lx-32-backend-down': ['for i in 1 2 3 4; do curl -s http://netlab.lab.local/app/; done', 'curl http://192.168.2.51:8080', 'app2: systemctl status app', 'app2: sudo systemctl start app', 'for i in 1 2 3 4; do curl -s http://netlab.lab.local/app/; done'],
    'lx-33-exam-web-front-end': ['sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/www.key -out /etc/ssl/certs/www.crt -subj "/CN=www.lab.local"', 'sudo mkdir -p /var/www/www', 'echo "<h1>Production site</h1>" | sudo tee /var/www/www/index.html', ...TEE('/etc/nginx/conf.d/www.conf', 'upstream backend {', '    least_conn;', '    server 192.168.2.50:8080;', '    server 192.168.2.51:8080;', '}', 'server {', '    listen 80;', '    server_name www.lab.local;', '    return 301 https://$host$request_uri;', '}', 'server {', '    listen 443 ssl;', '    server_name www.lab.local;', '    ssl_certificate /etc/ssl/certs/www.crt;', '    ssl_certificate_key /etc/ssl/private/www.key;', '    add_header Strict-Transport-Security "max-age=31536000" always;', '    root /var/www/www;', '    index index.html;', '    location /api/ {', '        proxy_pass http://backend/;', '        proxy_set_header Host $host;', '    }', '}'), 'sudo nginx -t', 'sudo systemctl enable --now nginx', 'echo "127.0.0.1 www.lab.local" | sudo tee -a /etc/hosts', 'curl -I http://www.lab.local', 'curl -kI https://www.lab.local', 'for i in 1 2 3 4; do curl -sk https://www.lab.local/api/; done'],
  });

  const A_TLS = ['<VirtualHost *:80>', '    ServerName netlab.lab.local', '    DocumentRoot /var/www/netlab', '</VirtualHost>', '<VirtualHost *:443>', '    ServerName netlab.lab.local', '    DocumentRoot /var/www/netlab', '    SSLEngine on', '    SSLCertificateFile /etc/ssl/certs/netlab.crt', '    SSLCertificateKeyFile /etc/ssl/private/netlab.key', '</VirtualHost>'];
  const A_CERT = 'sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/netlab.key -out /etc/ssl/certs/netlab.crt -subj "/CN=netlab.lab.local"';
  Object.assign(solutions, {
    'lx-34-install-apache': ['sudo apt install -y apache2', 'ls /etc/apache2', 'ls -l /etc/apache2/sites-enabled', 'sudo apache2ctl configtest', 'sudo apache2ctl -M', 'curl http://192.168.1.50', 'PC-A: curl http://192.168.1.50'],
    'lx-35-apache-virtual-host': [...TEE('/etc/apache2/sites-available/netlab.conf', '<VirtualHost *:80>', '    ServerName netlab.lab.local', '    DocumentRoot /var/www/netlab', '</VirtualHost>'), 'sudo a2ensite netlab', 'curl http://netlab.lab.local', 'sudo apache2ctl configtest', 'sudo systemctl reload apache2', 'curl http://netlab.lab.local', 'curl -H "Host: nobody.example" http://192.168.1.50'],
    'lx-36-troubleshoot-apache': ['sudo systemctl start apache2', 'sudo apache2ctl configtest', "sudo sed -i 's/DocumnetRoot/DocumentRoot/' /etc/apache2/sites-available/netlab.conf", "echo '</VirtualHost>' | sudo tee -a /etc/apache2/sites-available/netlab.conf", 'sudo apache2ctl configtest', 'sudo systemctl start apache2', 'curl http://netlab.lab.local'],
    'lx-37-apache-tls': [...TEE('/etc/apache2/sites-available/netlab.conf', ...A_TLS), 'sudo apache2ctl configtest', 'sudo a2enmod ssl', A_CERT, 'sudo apache2ctl configtest', 'sudo systemctl restart apache2', 'ss -tln', 'curl https://netlab.lab.local', 'curl -k https://netlab.lab.local'],
    'lx-38-apache-redirect-hsts': [
      ...TEE('/etc/apache2/sites-available/netlab.conf', '<VirtualHost *:80>', '    ServerName netlab.lab.local', '    Redirect permanent / https://netlab.lab.local/', '</VirtualHost>', '<VirtualHost *:443>', '    ServerName netlab.lab.local', '    DocumentRoot /var/www/netlab', '    SSLEngine on', '    SSLCertificateFile /etc/ssl/certs/netlab.crt', '    SSLCertificateKeyFile /etc/ssl/private/netlab.key', '    Header always set Strict-Transport-Security "max-age=31536000"', '</VirtualHost>'),
      'sudo a2enmod headers', 'sudo apache2ctl configtest', 'sudo systemctl restart apache2', 'curl -I http://netlab.lab.local', 'curl -kLi http://netlab.lab.local',
    ],
    'lx-39-apache-reverse-proxy': [
      'curl http://192.168.2.50:8080',
      ...TEE('/etc/apache2/sites-available/netlab.conf', '<VirtualHost *:80>', '    ServerName netlab.lab.local', '    DocumentRoot /var/www/netlab', '    ProxyPass /app/ http://192.168.2.50:8080/', '    ProxyPassReverse /app/ http://192.168.2.50:8080/', '</VirtualHost>'),
      'sudo a2enmod proxy', 'sudo apache2ctl configtest', 'sudo systemctl restart apache2', 'curl http://netlab.lab.local/app/', 'sudo a2enmod proxy_http', 'sudo systemctl restart apache2', 'curl http://netlab.lab.local/app/', 'curl http://netlab.lab.local/',
    ],
    'lx-40-apache-load-balancing': [
      'sudo a2enmod proxy_balancer lbmethod_byrequests',
      ...TEE('/etc/apache2/sites-available/netlab.conf', '<VirtualHost *:80>', '    ServerName netlab.lab.local', '    DocumentRoot /var/www/netlab', '    <Proxy balancer://cluster>', '        BalancerMember http://192.168.2.50:8080', '        BalancerMember http://192.168.2.51:8080', '    </Proxy>', '    ProxyPass /app/ balancer://cluster/', '</VirtualHost>'),
      'sudo apache2ctl configtest', 'sudo systemctl restart apache2', 'for i in 1 2 3 4; do curl -s http://netlab.lab.local/app/; done',
    ],
    'lx-41-apache-port-conflict': ['sudo systemctl start apache2', 'systemctl status apache2', 'sudo ss -tlnp', 'sudo systemctl disable --now nginx', 'sudo systemctl enable --now apache2', 'curl http://192.168.1.50'],
    'lx-42-exam-apache-front-end': [
      'sudo a2enmod ssl headers proxy proxy_http proxy_balancer lbmethod_byrequests',
      'sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/www.key -out /etc/ssl/certs/www.crt -subj "/CN=www.lab.local"',
      'sudo mkdir -p /var/www/www',
      'echo "<h1>Production site</h1>" | sudo tee /var/www/www/index.html',
      ...TEE(
        '/etc/apache2/sites-available/www.conf',
        '<VirtualHost *:80>',
        '    ServerName www.lab.local',
        '    Redirect permanent / https://www.lab.local/',
        '</VirtualHost>',
        '<VirtualHost *:443>',
        '    ServerName www.lab.local',
        '    DocumentRoot /var/www/www',
        '    SSLEngine on',
        '    SSLCertificateFile /etc/ssl/certs/www.crt',
        '    SSLCertificateKeyFile /etc/ssl/private/www.key',
        '    Header always set Strict-Transport-Security "max-age=31536000"',
        '    <Proxy balancer://cluster>',
        '        BalancerMember http://192.168.2.50:8080',
        '        BalancerMember http://192.168.2.51:8080',
        '    </Proxy>',
        '    ProxyPass /api/ balancer://cluster/',
        '</VirtualHost>',
      ),
      'sudo a2ensite www', 'sudo apache2ctl configtest', 'sudo systemctl restart apache2',
      'curl -I http://www.lab.local', 'curl -kI https://www.lab.local', 'for i in 1 2 3 4; do curl -sk https://www.lab.local/api/; done',
    ],
  });

  // SQL labs open at the psql prompt on db1, so every line below is SQL unless it starts with a backslash.
  Object.assign(solutions, {
    'db-01-first-query': ['db1: \\dt', 'db1: \\d products', 'db1: SELECT * FROM products;', 'db1: SELECT name, price FROM products;'],
    'db-02-choose-rows': [
      "db1: SELECT name FROM customers WHERE city = 'London';",
      'db1: SELECT name, price FROM products WHERE price > 50;',
      "db1: SELECT name FROM products WHERE category IN ('coffee', 'tableware');",
      "db1: SELECT name FROM products WHERE name LIKE '%Beans%';",
      "db1: SELECT id FROM orders WHERE placed BETWEEN '2026-02-01' AND '2026-02-28';",
    ],
    'db-03-sort-and-limit': [
      'db1: SELECT name, price FROM products ORDER BY price;',
      'db1: SELECT name, price FROM products ORDER BY price DESC LIMIT 3;',
      'db1: SELECT DISTINCT category FROM products;',
      'db1: SELECT name, joined FROM customers ORDER BY joined DESC LIMIT 3;',
    ],
    'db-04-missing-values': [
      'db1: SELECT name FROM customers WHERE email = NULL;',
      'db1: SELECT name FROM customers WHERE email IS NULL;',
      'db1: SELECT name FROM customers WHERE email IS NOT NULL;',
      'db1: SELECT count(*) FROM customers WHERE city IS NOT NULL;',
      "db1: SELECT name, coalesce(city, 'unknown') FROM customers;",
    ],
    'db-05-join-two-tables': [
      'db1: SELECT c.name, o.id, o.placed FROM customers c JOIN orders o ON o.customer_id = c.id;',
      'db1: SELECT o.id, p.name, i.quantity FROM orders o JOIN order_items i ON i.order_id = o.id JOIN products p ON p.id = i.product_id;',
      "db1: SELECT p.name FROM customers c JOIN orders o ON o.customer_id = c.id JOIN order_items i ON i.order_id = o.id JOIN products p ON p.id = i.product_id WHERE c.name = 'Ada Lovelace';",
    ],
    'db-06-keep-every-row': [
      'db1: SELECT DISTINCT c.name FROM customers c JOIN orders o ON o.customer_id = c.id;',
      'db1: SELECT c.name, o.id FROM customers c LEFT JOIN orders o ON o.customer_id = c.id;',
      'db1: SELECT c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL;',
    ],
    'db-07-summarise': [
      'db1: SELECT category, count(*) FROM products GROUP BY category;',
      'db1: SELECT category, round(avg(price), 2) FROM products GROUP BY category;',
      'db1: SELECT o.id, sum(i.quantity * i.unit_price) FROM orders o JOIN order_items i ON i.order_id = o.id GROUP BY o.id;',
      'db1: SELECT customer_id FROM orders GROUP BY customer_id HAVING count(*) > 1;',
    ],
    'db-08-questions-inside-questions': [
      'db1: SELECT name FROM products WHERE id NOT IN (SELECT product_id FROM order_items);',
      "db1: SELECT name FROM customers WHERE id IN (SELECT customer_id FROM orders WHERE placed BETWEEN '2026-02-01' AND '2026-02-28');",
      'db1: SELECT name FROM products WHERE price > (SELECT avg(price) FROM products);',
      'db1: SELECT name FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);',
    ],
    'db-09-add-rows': [
      "db1: INSERT INTO customers (name, city, email, joined) VALUES ('Gus Weber', 'Bristol', 'gus@example.com', '2026-03-05');",
      "db1: INSERT INTO products (sku, name, category, price, stock) VALUES ('TMP-700', 'Milk Thermometer', 'appliances', 12.75, 15);",
      "db1: INSERT INTO products (sku, name, category, price, stock) VALUES ('CUP-402', 'Cappuccino Cup', 'tableware', 5.75, 60), ('SAU-403', 'Saucer', 'tableware', 3.25, 80);",
    ],
    'db-10-change-and-remove': [
      "db1: UPDATE products SET price = 259.00 WHERE sku = 'ESP-100';",
      "db1: UPDATE orders SET status = 'shipped' WHERE id = 5;",
      "db1: DELETE FROM products WHERE sku = 'FLT-500';",
      "db1: DELETE FROM customers WHERE name = 'Ada Lovelace';",
    ],
    'db-11-all-or-nothing': [
      'db1: BEGIN;',
      'db1: UPDATE products SET price = round(price * 1.1, 2);',
      'db1: SELECT name, price FROM products;',
      'db1: ROLLBACK;',
      'db1: BEGIN;',
      "db1: UPDATE products SET price = round(price * 1.1, 2) WHERE category = 'coffee';",
      'db1: COMMIT;',
    ],
    'db-12-create-a-table': [
      "db1: CREATE TABLE suppliers (id serial PRIMARY KEY, name text NOT NULL, country text NOT NULL DEFAULT 'UK', active boolean NOT NULL DEFAULT true, since date);",
      "db1: INSERT INTO suppliers (name, country, since) VALUES ('Bean Bros', 'UK', '2025-01-15');",
      "db1: INSERT INTO suppliers (name, country, since) VALUES ('Milano Machines', 'Italy', '2025-08-02');",
      'db1: \\d suppliers',
    ],
    'db-13-keys-and-rules': [
      'db1: CREATE TABLE coupons (code text PRIMARY KEY, percent integer NOT NULL CHECK (percent > 0 AND percent <= 50), expires date NOT NULL, uses integer NOT NULL DEFAULT 0);',
      "db1: INSERT INTO coupons (code, percent, expires) VALUES ('SPRING10', 10, '2026-06-30');",
      "db1: INSERT INTO coupons (code, percent, expires) VALUES ('SPRING10', 15, '2026-07-31');",
      "db1: INSERT INTO coupons (code, percent, expires) VALUES ('HALFOFF', 90, '2026-06-30');",
    ],
    'db-14-link-tables': [
      'db1: CREATE TABLE shipments (id serial PRIMARY KEY, order_id integer NOT NULL REFERENCES orders (id), courier text NOT NULL, sent date NOT NULL);',
      "db1: INSERT INTO shipments (order_id, courier, sent) VALUES (1, 'DPD', '2026-01-07');",
      "db1: INSERT INTO shipments (order_id, courier, sent) VALUES (99, 'DPD', '2026-01-07');",
    ],
    'db-15-change-the-shape': [
      'db1: ALTER TABLE customers ADD COLUMN phone text;',
      'db1: ALTER TABLE customers ADD COLUMN loyalty text NOT NULL;',
      "db1: ALTER TABLE customers ADD COLUMN loyalty text NOT NULL DEFAULT 'bronze';",
      'db1: ALTER TABLE customers RENAME COLUMN joined TO signed_up;',
      'db1: ALTER TABLE customers DROP COLUMN phone;',
    ],
    'db-16-see-the-plan': [
      "db1: EXPLAIN SELECT * FROM orders WHERE placed = '2026-02-14';",
      "db1: EXPLAIN SELECT * FROM products WHERE category = 'coffee';",
      "db1: EXPLAIN ANALYZE SELECT * FROM orders WHERE placed = '2026-02-14';",
    ],
    'db-17-add-an-index': [
      'db1: CREATE INDEX orders_placed_idx ON orders (placed);',
      "db1: EXPLAIN SELECT * FROM orders WHERE placed = '2026-02-14';",
      'db1: CREATE INDEX products_category_idx ON products (category);',
      'db1: \\di',
    ],
    'db-18-save-a-query': [
      'db1: CREATE VIEW order_totals AS SELECT o.id, c.name AS customer, sum(i.quantity * i.unit_price) AS total FROM orders o JOIN customers c ON c.id = o.customer_id JOIN order_items i ON i.order_id = o.id GROUP BY o.id, c.name;',
      'db1: SELECT * FROM order_totals ORDER BY total DESC;',
      'db1: SELECT * FROM order_totals WHERE total > 100;',
    ],
    'db-19-exam-the-monthly-report': [
      "db1: SELECT sum(i.quantity * i.unit_price) FROM orders o JOIN order_items i ON i.order_id = o.id WHERE o.status = 'shipped';",
      "db1: SELECT c.name, sum(i.quantity * i.unit_price) AS spend FROM customers c JOIN orders o ON o.customer_id = c.id JOIN order_items i ON i.order_id = o.id WHERE o.status <> 'cancelled' GROUP BY c.name ORDER BY spend DESC LIMIT 3;",
      'db1: SELECT name FROM products WHERE id NOT IN (SELECT product_id FROM order_items);',
      'db1: SELECT category, round(avg(price), 2) FROM products GROUP BY category HAVING avg(price) > 20;',
      'db1: SELECT c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL;',
    ],
    'db-20-exam-design-a-schema': [
      'db1: CREATE TABLE warehouses (id serial PRIMARY KEY, code text NOT NULL UNIQUE, city text NOT NULL);',
      'db1: CREATE TABLE stock_moves (id serial PRIMARY KEY, product_id integer NOT NULL REFERENCES products (id), warehouse_id integer NOT NULL REFERENCES warehouses (id), moved date NOT NULL, quantity integer NOT NULL CHECK (quantity <> 0));',
      "db1: INSERT INTO warehouses (code, city) VALUES ('LDN', 'London'), ('BRS', 'Bristol');",
      "db1: INSERT INTO stock_moves (product_id, warehouse_id, moved, quantity) VALUES (1, 1, '2026-03-02', 10), (3, 1, '2026-03-02', 25), (2, 2, '2026-03-03', -4);",
      "db1: INSERT INTO warehouses (code, city) VALUES ('LDN', 'Leeds');",
      "db1: INSERT INTO stock_moves (product_id, warehouse_id, moved, quantity) VALUES (1, 1, '2026-03-04', 0);",
      "db1: INSERT INTO stock_moves (product_id, warehouse_id, moved, quantity) VALUES (999, 1, '2026-03-04', 5);",
      'db1: SELECT w.code, sum(m.quantity) FROM warehouses w JOIN stock_moves m ON m.warehouse_id = w.id GROUP BY w.code;',
    ],
    'db-21-compute-and-name': [
      'db1: SELECT name, round(price * 1.2, 2) AS with_vat FROM products;',
      'db1: SELECT name, stock / 3 FROM products;',
      'db1: SELECT name, round(stock::numeric / 3, 2) FROM products;',
      "db1: SELECT name, CASE WHEN price >= 100 THEN 'premium' WHEN price >= 20 THEN 'standard' ELSE 'budget' END FROM products;",
      "db1: SELECT name || ' (' || category || ')' FROM products;",
    ],
    'db-22-read-a-schema': [
      'db1: \\dt',
      'db1: \\d loans',
      'db1: SELECT title FROM books b WHERE NOT EXISTS (SELECT 1 FROM loans l WHERE l.book_id = b.id);',
      'db1: SELECT b.title, m.name FROM loans l JOIN books b ON b.id = l.book_id JOIN members m ON m.id = l.member_id WHERE l.returned IS NULL;',
      'db1: SELECT m.name, count(*) FROM members m JOIN loans l ON l.member_id = m.id GROUP BY m.name;',
    ],
    'db-23-many-to-many': [
      "db1: SELECT DISTINCT c.name FROM customers c JOIN orders o ON o.customer_id = c.id JOIN order_items i ON i.order_id = o.id JOIN products p ON p.id = i.product_id WHERE p.name = 'Ethiopia Beans 1kg';",
      'db1: SELECT c.name, count(DISTINCT i.product_id) FROM customers c JOIN orders o ON o.customer_id = c.id JOIN order_items i ON i.order_id = o.id GROUP BY c.name;',
      'db1: SELECT p.name, count(DISTINCT o.customer_id) FROM products p JOIN order_items i ON i.product_id = p.id JOIN orders o ON o.id = i.order_id GROUP BY p.name;',
      "db1: SELECT name FROM products WHERE id NOT IN (SELECT i.product_id FROM orders o JOIN order_items i ON i.order_id = o.id JOIN customers c ON c.id = o.customer_id WHERE c.name = 'Ada Lovelace');",
    ],
    'db-24-stack-results': [
      "db1: SELECT customer_id FROM orders WHERE placed < '2026-02-01' UNION SELECT customer_id FROM orders WHERE placed >= '2026-02-01';",
      "db1: SELECT customer_id FROM orders WHERE placed < '2026-02-01' UNION ALL SELECT customer_id FROM orders WHERE placed >= '2026-02-01';",
      "db1: SELECT customer_id FROM orders WHERE placed < '2026-02-01' INTERSECT SELECT customer_id FROM orders WHERE placed >= '2026-02-01';",
      "db1: SELECT customer_id FROM orders WHERE placed < '2026-02-01' EXCEPT SELECT customer_id FROM orders WHERE placed >= '2026-02-01';",
    ],
    'db-25-copy-and-archive': [
      'db1: CREATE TABLE orders_archive (id integer PRIMARY KEY, customer_id integer NOT NULL, placed date NOT NULL, status text NOT NULL);',
      "db1: INSERT INTO orders_archive (id, customer_id, placed, status) SELECT id, customer_id, placed, status FROM orders WHERE status = 'cancelled';",
      'db1: DELETE FROM order_items WHERE order_id IN (SELECT id FROM orders_archive);',
      'db1: DELETE FROM orders WHERE id IN (SELECT id FROM orders_archive);',
    ],
    'db-26-update-from-what-you-find': [
      "db1: UPDATE orders SET status = 'closed' WHERE customer_id = (SELECT id FROM customers WHERE name = 'Ada Lovelace');",
      'db1: UPDATE products SET stock = 0 WHERE id NOT IN (SELECT product_id FROM order_items);',
      'db1: UPDATE products SET price = round(price * 0.95, 2) WHERE category IN (SELECT category FROM products GROUP BY category HAVING avg(price) > 100);',
    ],
    'db-27-find-and-fix-duplicates': [
      'db1: SELECT email, count(*) FROM subscribers GROUP BY email HAVING count(*) > 1;',
      'db1: ALTER TABLE subscribers ADD UNIQUE (email);',
      'db1: DELETE FROM subscribers WHERE id NOT IN (SELECT min(id) FROM subscribers GROUP BY email);',
      'db1: ALTER TABLE subscribers ADD UNIQUE (email);',
      "db1: INSERT INTO subscribers (email, signed_up) VALUES ('ada@example.com', '2026-03-01');",
    ],
    'db-28-model-a-choice': [
      'db1: CREATE TABLE tags (id serial PRIMARY KEY, name text NOT NULL UNIQUE);',
      'db1: CREATE TABLE product_tags (product_id integer NOT NULL REFERENCES products (id), tag_id integer NOT NULL REFERENCES tags (id), PRIMARY KEY (product_id, tag_id));',
      "db1: INSERT INTO tags (name) VALUES ('gift'), ('sale'), ('new');",
      'db1: INSERT INTO product_tags (product_id, tag_id) VALUES (1, 1), (1, 2), (2, 1);',
      "db1: SELECT p.name FROM products p JOIN product_tags pt ON pt.product_id = p.id JOIN tags t ON t.id = pt.tag_id WHERE t.name = 'gift';",
      'db1: INSERT INTO product_tags (product_id, tag_id) VALUES (1, 1);',
    ],
    'db-29-choose-the-right-index': [
      'db1: CREATE INDEX orders_status_placed_idx ON orders (status, placed);',
      "db1: EXPLAIN SELECT * FROM orders WHERE status = 'pending';",
      "db1: EXPLAIN SELECT * FROM orders WHERE placed = '2026-02-14';",
      'db1: CREATE UNIQUE INDEX customers_email_key ON customers (email);',
      "db1: INSERT INTO customers (name, city, email, joined) VALUES ('Impostor', 'Leeds', 'ada@example.com', '2026-03-01');",
      "db1: INSERT INTO customers (name, city, joined) VALUES ('Gus Weber', 'Hull', '2026-03-02'), ('Hana Ito', 'York', '2026-03-03');",
    ],
    'db-30-exam-clean-up-the-data': [
      'db1: SELECT count(*) FROM contacts WHERE email IS NULL;',
      'db1: SELECT email, count(*) FROM contacts WHERE email IS NOT NULL GROUP BY email HAVING count(*) > 1;',
      'db1: DELETE FROM contacts WHERE email IS NULL;',
      'db1: DELETE FROM contacts WHERE id NOT IN (SELECT min(id) FROM contacts GROUP BY email);',
      "db1: UPDATE contacts SET marketing = lower(coalesce(marketing, 'no'));",
      'db1: ALTER TABLE contacts ALTER COLUMN email SET NOT NULL;',
      'db1: ALTER TABLE contacts ADD UNIQUE (email);',
      'db1: ALTER TABLE contacts ALTER COLUMN marketing SET NOT NULL;',
      "db1: ALTER TABLE contacts ADD CHECK (marketing IN ('yes', 'no'));",
      "db1: INSERT INTO contacts (email, name, marketing) VALUES ('ada@example.com', 'Duplicate', 'no');",
      'db1: SELECT count(*) FROM contacts;',
      "db1: SELECT count(*) FROM contacts WHERE marketing = 'yes';",
    ],
  });

  // Terraform labs run on ops1 in ~/infra. Heredocs quote 'EOF' so ${...} reaches the file untouched.
  Object.assign(solutions, {
    'tf-01-first-apply': ['cat main.tf', 'terraform init', 'terraform plan', 'terraform apply', 'yes', 'cat welcome.txt'],
    'tf-02-change-and-destroy': ["sed -i 's/length = 2/length = 3/' main.tf", "sed -i 's/Your first server is called /Welcome aboard, /' main.tf", 'terraform plan', 'terraform apply -auto-approve', 'terraform destroy', 'yes'],
    'tf-03-validate-and-format': ['terraform init', 'terraform validate', "sed -i 's/lenght/length/' main.tf", "sed -i 's/var.enviroment/var.environment/' main.tf", 'terraform validate', 'terraform fmt -check', 'terraform fmt', 'terraform validate'],
    'tf-04-read-the-plan': ['terraform plan -out=change.tfplan', 'terraform show change.tfplan', "sed -i 's/mysql/postgres/' main.tf", 'terraform plan -out=change.tfplan', 'terraform apply change.tfplan'],
    'tf-05-pin-providers': ['terraform init', 'cat .terraform.lock.hcl', 'terraform validate', "sed -i 's/>= 1.0/~> 1.4/' versions.tf", 'terraform init', 'terraform init -upgrade', 'terraform validate', 'terraform apply -auto-approve'],
    'tf-06-build-a-network': [
      ...HEREDOC(
        'main.tf',
        'resource "netcloud_network" "main" {',
        '  name       = "web"',
        '  cidr_block = "10.10.0.0/16"',
        '}',
        '',
        'resource "netcloud_subnet" "web" {',
        '  network_id = netcloud_network.main.id',
        '  cidr_block = "10.10.1.0/24"',
        '  public     = true',
        '}',
        '',
        'resource "netcloud_firewall" "web" {',
        '  name       = "web"',
        '  network_id = netcloud_network.main.id',
        '',
        '  ingress {',
        '    port        = 22',
        '    cidr_blocks = ["0.0.0.0/0"]',
        '  }',
        '',
        '  ingress {',
        '    port        = 443',
        '    cidr_blocks = ["0.0.0.0/0"]',
        '  }',
        '}',
        '',
        'resource "netcloud_instance" "web" {',
        '  name         = "web"',
        '  size         = "small"',
        '  image        = "img-ubuntu-2404-20260901"',
        '  subnet_id    = netcloud_subnet.web.id',
        '  firewall_ids = [netcloud_firewall.web.id]',
        '}',
      ),
      'terraform init',
      'terraform plan',
      'terraform apply -auto-approve',
    ],
    'tf-07-two-regions': [
      'terraform apply -auto-approve',
      ...HEREDOC(
        'main.tf',
        'terraform {',
        '  required_providers {',
        '    netcloud = {',
        '      source  = "netlab/netcloud"',
        '      version = "~> 1.4"',
        '    }',
        '    random = {',
        '      source  = "hashicorp/random"',
        '      version = "~> 3.7"',
        '    }',
        '  }',
        '}',
        '',
        'provider "netcloud" {',
        '  region = "eu-west"',
        '}',
        '',
        'provider "netcloud" {',
        '  alias  = "us_east"',
        '  region = "us-east"',
        '}',
        '',
        'resource "random_id" "suffix" {',
        '  byte_length = 3',
        '}',
        '',
        'resource "netcloud_bucket" "backups" {',
        '  name       = "netlab-backups-${random_id.suffix.hex}"',
        '  versioning = true',
        '}',
        '',
        'resource "netcloud_bucket" "dr" {',
        '  provider   = netcloud.us_east',
        '  name       = "netlab-backups-dr-${random_id.suffix.hex}"',
        '  versioning = true',
        '}',
      ),
      'terraform init',
      'terraform apply -auto-approve',
    ],
    'tf-08-state-and-backups': ['terraform plan', 'cat terraform.tfstate.backup', 'cp terraform.tfstate.backup terraform.tfstate', 'terraform state list', 'terraform show', 'terraform plan', 'terraform apply -auto-approve'],
    'tf-09-variables-and-outputs': [
      ...HEREDOC('variables.tf', 'variable "env" {', '  type    = string', '  default = "dev"', '}', '', 'variable "cidr_block" {', '  type = string', '}'),
      'echo \'cidr_block = "10.20.0.0/16"\' > terraform.tfvars',
      ...HEREDOC('main.tf', 'resource "netcloud_network" "main" {', '  name       = "shop-${var.env}"', '  cidr_block = var.cidr_block', '}', '', 'resource "netcloud_subnet" "app" {', '  network_id = netcloud_network.main.id', '  cidr_block = cidrsubnet(var.cidr_block, 8, 1)', '}'),
      ...HEREDOC('outputs.tf', 'output "network_id" {', '  value = netcloud_network.main.id', '}', '', 'output "subnet_cidr" {', '  value = netcloud_subnet.app.cidr_block', '}'),
      'terraform init',
      'terraform apply -var="env=staging" -auto-approve',
      'terraform output',
    ],
    'tf-10-data-sources': [...HEREDOC('image.tf', 'data "netcloud_image" "ubuntu" {', '  family = "ubuntu-2404"', '}'), "sed -i 's/\"img-ubuntu-2204-20260815\"/data.netcloud_image.ubuntu.id/' main.tf", 'terraform plan', 'terraform apply -auto-approve', 'terraform state show data.netcloud_image.ubuntu'],
    'tf-11-count-and-for-each': [
      "cat >> main.tf << 'EOF'",
      '',
      'resource "netcloud_subnet" "this" {',
      '  for_each   = var.subnets',
      '  network_id = netcloud_network.main.id',
      '  name       = each.key',
      '  cidr_block = each.value',
      '}',
      '',
      'resource "netcloud_instance" "web" {',
      '  count     = var.web_count',
      '  name      = "web-${count.index}"',
      '  size      = "small"',
      '  image     = "img-ubuntu-2404-20260901"',
      '  subnet_id = netcloud_subnet.this["app"].id',
      '}',
      'EOF',
      'terraform init',
      'terraform apply -auto-approve',
      'terraform apply -var="web_count=1" -auto-approve',
    ],
    'tf-12-expressions-and-functions': [
      'terraform console',
      'var.network.subnets',
      'cidrsubnet(var.network.cidr, 8, 0)',
      '{ for i, s in var.network.subnets : s.name => cidrsubnet(var.network.cidr, 8, i) }',
      'exit',
      ...HEREDOC(
        'main.tf',
        'locals {',
        '  subnets = { for i, s in var.network.subnets : s.name => { cidr = cidrsubnet(var.network.cidr, 8, i), public = s.public } }',
        '  tags    = merge(var.common_tags, { network = var.network.name })',
        '}',
        '',
        'resource "netcloud_network" "main" {',
        '  name       = var.network.name',
        '  cidr_block = var.network.cidr',
        '  tags       = local.tags',
        '}',
        '',
        'resource "netcloud_subnet" "this" {',
        '  for_each   = local.subnets',
        '  network_id = netcloud_network.main.id',
        '  name       = each.key',
        '  cidr_block = each.value.cidr',
        '  public     = each.value.public',
        '}',
        '',
        'output "subnet_cidrs" {',
        '  value = { for k, s in netcloud_subnet.this : k => s.cidr_block }',
        '}',
      ),
      'terraform apply -auto-approve',
    ],
    'tf-13-dynamic-blocks': [
      ...HEREDOC(
        'variables.tf',
        'variable "ingress_rules" {',
        '  type = list(object({',
        '    port        = number',
        '    cidr_blocks = list(string)',
        '  }))',
        '  default = [',
        '    { port = 22, cidr_blocks = ["10.0.0.0/8"] },',
        '    { port = 80, cidr_blocks = ["0.0.0.0/0"] },',
        '    { port = 443, cidr_blocks = ["0.0.0.0/0"] },',
        '    { port = 8443, cidr_blocks = ["0.0.0.0/0"] },',
        '  ]',
        '}',
      ),
      ...HEREDOC(
        'main.tf',
        'resource "netcloud_network" "main" {',
        '  name       = "edge"',
        '  cidr_block = "10.60.0.0/16"',
        '}',
        '',
        'resource "netcloud_firewall" "edge" {',
        '  name       = "edge"',
        '  network_id = netcloud_network.main.id',
        '',
        '  dynamic "ingress" {',
        '    for_each = var.ingress_rules',
        '    content {',
        '      port        = ingress.value.port',
        '      cidr_blocks = ingress.value.cidr_blocks',
        '    }',
        '  }',
        '}',
      ),
      'terraform plan',
      'terraform apply -auto-approve',
    ],
    'tf-14-dependencies-and-lifecycle': [
      ...HEREDOC(
        'main.tf',
        'resource "netcloud_network" "main" {',
        '  name       = "orders"',
        '  cidr_block = "10.70.0.0/16"',
        '}',
        '',
        'resource "netcloud_subnet" "app" {',
        '  network_id = netcloud_network.main.id',
        '  cidr_block = "10.70.1.0/24"',
        '}',
        '',
        'resource "random_id" "logs" {',
        '  byte_length = 3',
        '}',
        '',
        'resource "netcloud_bucket" "logs" {',
        '  name = "orders-logs-${random_id.logs.hex}"',
        '}',
        '',
        'resource "netcloud_instance" "web" {',
        '  name       = "orders-web"',
        '  size       = "small"',
        '  image      = "img-ubuntu-2404-20260901"',
        '  subnet_id  = netcloud_subnet.app.id',
        '  user_data  = "LOG_BUCKET_PREFIX=orders-logs-"',
        '  depends_on = [netcloud_bucket.logs]',
        '',
        '  lifecycle {',
        '    create_before_destroy = true',
        '  }',
        '}',
        '',
        'resource "netcloud_database" "orders" {',
        '  name           = "orders"',
        '  engine         = "postgres"',
        '  engine_version = "16"',
        '  size           = "small"',
        '  password       = "orders-db-password-2026"',
        '',
        '  lifecycle {',
        '    prevent_destroy = true',
        '  }',
        '}',
      ),
      'terraform apply -auto-approve',
      'terraform destroy',
    ],
    'tf-15-custom-conditions': [
      ...HEREDOC(
        'variables.tf',
        'variable "instance_size" {',
        '  type    = string',
        '  default = "small"',
        '',
        '  validation {',
        '    condition     = contains(["small", "medium"], var.instance_size)',
        '    error_message = "instance_size must be small or medium."',
        '  }',
        '}',
        '',
        'variable "image_family" {',
        '  type    = string',
        '  default = "ubuntu-2404"',
        '}',
      ),
      'terraform plan -var="instance_size=xlarge"',
      ...HEREDOC(
        'main.tf',
        'resource "netcloud_network" "main" {',
        '  name       = "payments"',
        '  cidr_block = "10.80.0.0/16"',
        '}',
        '',
        'resource "netcloud_subnet" "app" {',
        '  network_id = netcloud_network.main.id',
        '  cidr_block = "10.80.1.0/24"',
        '}',
        '',
        'data "netcloud_image" "base" {',
        '  family = var.image_family',
        '}',
        '',
        'resource "netcloud_instance" "api" {',
        '  name      = "payments-api"',
        '  size      = var.instance_size',
        '  image     = data.netcloud_image.base.id',
        '  subnet_id = netcloud_subnet.app.id',
        '',
        '  lifecycle {',
        '    precondition {',
        '      condition     = strcontains(data.netcloud_image.base.name, "LTS")',
        '      error_message = "Use an LTS image."',
        '    }',
        '    postcondition {',
        '      condition     = self.public_ip == null',
        '      error_message = "The API must not have a public address."',
        '    }',
        '  }',
        '}',
        '',
        'check "api_running" {',
        '  assert {',
        '    condition     = netcloud_instance.api.status == "running"',
        '    error_message = "The API is not running."',
        '  }',
        '}',
      ),
      'terraform apply -auto-approve',
    ],
    'tf-16-secrets': [
      'cat versions.tf',
      'grep Sup3rSecret terraform.tfstate',
      "sed -i '/token  =/d' versions.tf",
      ...HEREDOC(
        'main.tf',
        'ephemeral "random_password" "db" {',
        '  length = 24',
        '}',
        '',
        'resource "netcloud_database" "orders" {',
        '  name                = "orders"',
        '  engine              = "postgres"',
        '  engine_version      = "16"',
        '  size                = "small"',
        '  password_wo         = ephemeral.random_password.db.result',
        '  password_wo_version = 1',
        '}',
        '',
        'output "db_endpoint" {',
        '  value = netcloud_database.orders.endpoint',
        '}',
      ),
      'terraform apply -auto-approve',
      'grep -c Sup3rSecret terraform.tfstate',
      'rm terraform.tfstate.backup',
    ],
    'tf-17-write-a-module': [
      'mkdir -p modules/web-tier',
      ...HEREDOC('modules/web-tier/variables.tf', 'variable "name" {', '  type = string', '}', '', 'variable "subnet_id" {', '  type = string', '}', '', 'variable "size" {', '  type    = string', '  default = "small"', '}'),
      ...HEREDOC('modules/web-tier/main.tf', 'resource "netcloud_instance" "this" {', '  name      = var.name', '  size      = var.size', '  image     = "img-ubuntu-2404-20260901"', '  subnet_id = var.subnet_id', '}'),
      ...HEREDOC('modules/web-tier/outputs.tf', 'output "private_ip" {', '  value = netcloud_instance.this.private_ip', '}'),
      "cat >> main.tf << 'EOF'",
      '',
      'module "web" {',
      '  source    = "./modules/web-tier"',
      '  name      = "intranet-web"',
      '  subnet_id = netcloud_subnet.app.id',
      '}',
      '',
      'output "web_ip" {',
      '  value = module.web.private_ip',
      '}',
      'EOF',
      'terraform init',
      'terraform apply -auto-approve',
    ],
    'tf-18-module-scope': ['terraform validate', ...HEREDOC('modules/network/outputs.tf', 'output "subnet_id" {', '  value = netcloud_subnet.this.id', '}'), "sed -i 's/module.network.netcloud_subnet.this.id/module.network.subnet_id/' main.tf", 'terraform validate', 'terraform apply -auto-approve'],
    'tf-19-registry-modules': [
      'terraform init',
      'cat .terraform/modules/vpc/README.md',
      'terraform apply -auto-approve',
      ...HEREDOC(
        'main.tf',
        'module "vpc" {',
        '  source  = "netlab/network/netcloud"',
        '  version = "~> 1.2"',
        '',
        '  name       = "reports"',
        '  cidr_block = "10.95.0.0/16"',
        '  subnets = {',
        '    app = { cidr = "10.95.1.0/24" }',
        '  }',
        '  tags = { team = "reports" }',
        '}',
        '',
        'output "app_subnet_id" {',
        '  value = module.vpc.subnet_ids["app"]',
        '}',
      ),
      'terraform init',
      'terraform apply -auto-approve',
    ],
    'tf-20-refactor-into-module': [
      ...HEREDOC(
        'main.tf',
        'module "network" {',
        '  source     = "./modules/network"',
        '  name       = "crm"',
        '  cidr_block = "10.97.0.0/16"',
        '}',
        '',
        'resource "netcloud_instance" "web" {',
        '  name      = "crm-web"',
        '  size      = "small"',
        '  image     = "img-ubuntu-2404-20260901"',
        '  subnet_id = module.network.subnet_id',
        '}',
      ),
      'terraform init',
      'terraform plan',
      "cat >> main.tf << 'EOF'",
      '',
      'moved {',
      '  from = netcloud_network.main',
      '  to   = module.network.netcloud_network.this',
      '}',
      '',
      'moved {',
      '  from = netcloud_subnet.app',
      '  to   = module.network.netcloud_subnet.app',
      '}',
      'EOF',
      'terraform plan',
      'terraform apply -auto-approve',
    ],
    'tf-21-inspect-and-rename': [
      'terraform state list',
      'terraform state show netcloud_instance.instance1',
      "sed -i 's/\"instance1\"/\"web\"/' main.tf",
      'terraform state mv netcloud_instance.instance1 netcloud_instance.web',
      "sed -i 's/\"netcloud_bucket\" \"bucket\"/\"netcloud_bucket\" \"assets\"/' main.tf",
      ...HEREDOC('moved.tf', 'moved {', '  from = netcloud_bucket.bucket', '  to   = netcloud_bucket.assets', '}'),
      'terraform plan',
      'terraform apply -auto-approve',
    ],
    'tf-22-drift': [
      'terraform plan -refresh-only',
      'netcloud activity',
      ...HEREDOC(
        'main.tf',
        'resource "netcloud_network" "main" {',
        '  name       = "search"',
        '  cidr_block = "10.14.0.0/16"',
        '}',
        '',
        'resource "netcloud_subnet" "app" {',
        '  network_id = netcloud_network.main.id',
        '  cidr_block = "10.14.1.0/24"',
        '}',
        '',
        'resource "netcloud_instance" "web" {',
        '  name      = "search-web"',
        '  size      = "small"',
        '  image     = "img-ubuntu-2404-20260901"',
        '  subnet_id = netcloud_subnet.app.id',
        '',
        '  tags = {',
        '    owner = "search-team"',
        '  }',
        '',
        '  lifecycle {',
        '    ignore_changes = [tags]',
        '  }',
        '}',
      ),
      'terraform plan',
      'terraform apply -auto-approve',
    ],
    'tf-23-import': [
      'netcloud instances list',
      'netcloud buckets show netlab-legacy-assets',
      ...HEREDOC('imports.tf', 'import {', '  to = netcloud_instance.legacy', '  id = "i-9c0d1e2f"', '}'),
      'terraform init',
      'terraform plan -generate-config-out=generated.tf',
      'cat generated.tf',
      'terraform apply -auto-approve',
      ...HEREDOC('bucket.tf', 'resource "netcloud_bucket" "assets" {', '  name          = "netlab-legacy-assets"', '  versioning    = true', '  force_destroy = false', '  tags          = { owner = "web-team" }', '}'),
      'terraform import netcloud_bucket.assets netlab-legacy-assets',
      'terraform plan',
    ],
    'tf-24-remote-state': [
      ...HEREDOC('backend.tf', 'terraform {', '  backend "http" {', '    address        = "https://state.netlab.cloud/teams/network/infra.tfstate"', '    lock_address   = "https://state.netlab.cloud/teams/network/infra.tfstate/lock"', '    unlock_address = "https://state.netlab.cloud/teams/network/infra.tfstate/lock"', '  }', '}'),
      'terraform plan',
      'terraform init',
      'yes',
      'terraform plan',
      'rm terraform.tfstate terraform.tfstate.backup',
    ],
    'tf-25-stale-lock': ['terraform plan', 'terraform force-unlock 6f3c2a1e-8b4d-4c5e-9a7b-2d1e0f3a4b5c', 'yes', 'terraform plan', 'terraform apply -auto-approve'],
    'tf-26-workspaces': ['terraform init', 'terraform workspace new dev', 'terraform apply -auto-approve', 'terraform workspace new prod', 'terraform apply -auto-approve', 'terraform workspace list', 'terraform workspace select dev'],
    'tf-28-hcp-remote-runs': [
      'cat ~/hcp-token.txt',
      'terraform login',
      'yes',
      'hcp.nlb.7Qx2mR9vK4tW',
      ...HEREDOC('cloud.tf', 'terraform {', '  cloud {', '    organization = "netlab-academy"', '', '    workspaces {', '      name = "network-dev"', '    }', '  }', '}'),
      'terraform init',
      'terraform plan',
      'terraform apply',
      'yes',
    ],
    'tf-29-hcp-workspaces-projects': ['terraform init', 'terraform workspace list', 'terraform workspace select network-prod', 'terraform workspace new network-staging', 'terraform workspace show'],
    'tf-30-policy-as-code': [
      'terraform plan',
      ...HEREDOC(
        'main.tf',
        'resource "netcloud_network" "main" {',
        '  name       = "network-dev"',
        '  cidr_block = "10.30.0.0/16"',
        '  tags       = { owner = "analytics" }',
        '}',
        '',
        'resource "netcloud_subnet" "app" {',
        '  network_id = netcloud_network.main.id',
        '  cidr_block = "10.30.1.0/24"',
        '}',
        '',
        'resource "netcloud_instance" "analytics" {',
        '  name      = "analytics"',
        '  size      = "medium"',
        '  image     = "img-ubuntu-2404-20260901"',
        '  subnet_id = netcloud_subnet.app.id',
        '  tags      = { owner = "analytics" }',
        '}',
      ),
      'terraform plan',
      'terraform apply',
      'yes',
    ],
    'tf-31-exam-production-network': [
      'cat requirements.md',
      ...HEREDOC(
        'versions.tf',
        'terraform {',
        '  required_providers {',
        '    netcloud = {',
        '      source  = "netlab/netcloud"',
        '      version = "~> 1.4"',
        '    }',
        '    random = {',
        '      source  = "hashicorp/random"',
        '      version = "~> 3.7"',
        '    }',
        '  }',
        '}',
        '',
        'provider "netcloud" {',
        '  region = "eu-west"',
        '}',
      ),
      ...HEREDOC('variables.tf', 'variable "env" {', '  type    = string', '  default = "prod"', '', '  validation {', '    condition     = contains(["dev", "staging", "prod"], var.env)', '    error_message = "env must be dev, staging or prod."', '  }', '}'),
      ...HEREDOC(
        'main.tf',
        'data "netcloud_image" "ubuntu" {',
        '  family = "ubuntu-2404"',
        '}',
        '',
        'resource "netcloud_network" "main" {',
        '  name       = "${var.env}-net"',
        '  cidr_block = "10.50.0.0/16"',
        '}',
        '',
        'locals {',
        '  subnets = {',
        '    web = { cidr = "10.50.1.0/24", public = true }',
        '    db  = { cidr = "10.50.2.0/24", public = false }',
        '  }',
        '}',
        '',
        'resource "netcloud_subnet" "this" {',
        '  for_each   = local.subnets',
        '  network_id = netcloud_network.main.id',
        '  name       = each.key',
        '  cidr_block = each.value.cidr',
        '  public     = each.value.public',
        '}',
        '',
        'resource "netcloud_firewall" "web" {',
        '  name       = "web"',
        '  network_id = netcloud_network.main.id',
        '',
        '  ingress {',
        '    port        = 443',
        '    cidr_blocks = ["0.0.0.0/0"]',
        '  }',
        '}',
        '',
        'resource "netcloud_instance" "web" {',
        '  count        = 2',
        '  name         = "web-${count.index}"',
        '  size         = "medium"',
        '  image        = data.netcloud_image.ubuntu.id',
        '  subnet_id    = netcloud_subnet.this["web"].id',
        '  firewall_ids = [netcloud_firewall.web.id]',
        '}',
        '',
        'ephemeral "random_password" "db" {',
        '  length = 24',
        '}',
        '',
        'resource "netcloud_database" "orders" {',
        '  name                = "orders"',
        '  engine              = "postgres"',
        '  engine_version      = "16"',
        '  size                = "small"',
        '  password_wo         = ephemeral.random_password.db.result',
        '  password_wo_version = 1',
        '',
        '  lifecycle {',
        '    prevent_destroy = true',
        '  }',
        '}',
      ),
      ...HEREDOC('outputs.tf', 'output "web_ips" {', '  value = netcloud_instance.web[*].private_ip', '}', '', 'output "db_endpoint" {', '  value = netcloud_database.orders.endpoint', '}'),
      'terraform init',
      'terraform apply -auto-approve',
      'terraform fmt',
      'terraform plan',
    ],
    'tf-32-exam-take-over-an-estate': [
      'cat handover.md',
      "sed -i '/token  =/d' versions.tf",
      "sed -i 's/\"server1\"/\"web\"/' main.tf",
      "cat >> main.tf << 'EOF'",
      '',
      'moved {',
      '  from = netcloud_instance.server1',
      '  to   = netcloud_instance.web',
      '}',
      '',
      'import {',
      '  to = netcloud_bucket.archive',
      '  id = "netlab-reports-archive"',
      '}',
      '',
      'resource "netcloud_bucket" "archive" {',
      '  name          = "netlab-reports-archive"',
      '  versioning    = true',
      '  force_destroy = false',
      '  tags          = { team = "reports" }',
      '}',
      'EOF',
      'terraform plan',
      'terraform apply -auto-approve',
      ...HEREDOC('backend.tf', 'terraform {', '  backend "http" {', '    address        = "https://state.netlab.cloud/teams/reports/infra.tfstate"', '    lock_address   = "https://state.netlab.cloud/teams/reports/infra.tfstate/lock"', '    unlock_address = "https://state.netlab.cloud/teams/reports/infra.tfstate/lock"', '  }', '}'),
      'terraform init',
      'yes',
      'rm terraform.tfstate terraform.tfstate.backup',
      'terraform fmt',
      'terraform plan',
    ],
    'tf-27-verbose-logging': ['terraform apply -auto-approve', 'TF_LOG=DEBUG TF_LOG_PATH=terraform.log terraform apply -auto-approve', 'grep -i 403 terraform.log', 'netcloud instances list', 'netcloud instances delete i-0hack001', 'netcloud instances delete i-0hack002', 'terraform apply -auto-approve'],
  });

  const HOME = '/home/student';
  const fakes: Record<string, Fake> = {
    'lx-20-hello-python': (p) => ({ stdout: p.argv[0] === '-c' ? 'Hello from Python\n' : 'Hello, NetLab!\n' }),
    'lx-21-read-files-with-python': () => ({ stdout: '2 errors\n', files: { [`${HOME}/summary.txt`]: '2026-09-11 08:57:44 ERROR disk full while writing /var/lib/app/cache\n2026-09-11 08:58:10 ERROR timeout talking to 192.168.2.50:5432\n' } }),
    'lx-22-read-json-with-python': () => ({ stdout: 'Site2-R2\nGigabitEthernet0/0 192.168.2.1\nGigabitEthernet0/1 10.0.0.2\n' }),
    'lx-23-generate-config-from-json': () => ({ files: { [`${HOME}/r2.cfg`]: ['hostname Site2-R2', 'interface GigabitEthernet0/0', ' description Site 2 LAN', ' ip address 192.168.2.1 255.255.255.0', ' no shutdown', 'interface GigabitEthernet0/1', ' description Link to R1', ' ip address 10.0.0.2 255.255.255.252', ' no shutdown', 'ip route 192.168.1.0 255.255.255.0 10.0.0.1', 'ntp server 192.168.1.50', ''].join('\n') } }),
    'lx-24-exam-audit-the-server': () => ({ stdout: '4 failed logins\n', files: { [`${HOME}/users.csv`]: 'student,1000,/bin/bash\nbob,1001,/bin/bash\n', [`${HOME}/audit.json`]: '{\n  "users": [\n    "student",\n    "bob"\n  ],\n  "failed_logins": 4\n}' } }),
  };

  it('covers every lab', () => {
    expect(Object.keys(solutions).sort()).toEqual(labs.map((l) => l.id).sort());
  });

  for (const lab of labs) {
    it(lab.id, () => {
      pythonFake = fakes[lab.id] ?? (() => ({}));
      const net = run(labNetwork(lab), ...(solutions[lab.id] ?? []));
      const result = grade(lab.objectives, net);
      const failing = result.objectives.filter((o) => !o.passed).map((o) => `${o.label}: ${o.checks.filter((c) => !c.passed).map((c) => c.label).join(', ')}`);
      expect(failing).toEqual([]);
      expect(result.passed).toBe(true);
      expect(result.score).toBe(100);
    });
  }
});

describe('only commands the device actually ran count', () => {
  const cli = labs.find((l) => l.id === 'cli-01-first-contact')!;
  const startCli = () => labNetwork(cli);
  const ranIt = (net: NetworkState, pattern: string, device?: string) => evaluateCheck({ type: 'command', pattern, ...(device ? { device } : {}) }, net);

  it('ignores a command the CLI rejected, however close to the real one it looks', () => {
    expect(ranIt(run(startCli(), 'enable', 'show ip intttterface brief'), '^(do )?show ip int')).toBe(false);
    // The same pattern is met as soon as the command actually runs.
    expect(ranIt(run(startCli(), 'enable', 'show ip interface brief'), '^(do )?show ip int')).toBe(true);
  });

  it('counts an abbreviation, by what was typed and by what it expanded to', () => {
    const net = run(startCli(), 'enable', 'sh ip int br');
    expect(ranIt(net, '^(do )?show ip interface brief$')).toBe(true);
    expect(ranIt(net, '^sh ip int br$')).toBe(true);
  });

  it('ignores a command the CLI called incomplete', () => {
    const net = run(startCli(), 'enable', 'configure');
    expect(net.devices[net.primary].commandHistory).toContain('configure');
    expect(ranIt(net, '^configure')).toBe(false);
  });

  it('keeps every attempt in the history the device prints', () => {
    // "show history" is meant to be a faithful record, mistakes included.
    const net = run(startCli(), 'enable', 'show ip intttterface brief');
    expect(net.devices[net.primary].commandHistory).toContain('show ip intttterface brief');
    expect(net.devices[net.primary].acceptedHistory).not.toContain('show ip intttterface brief');
  });

  it('ignores a name the Linux shell could not find', () => {
    const lab = labs.find((l) => l.id.startsWith('lx-'))!;
    const host = Object.values(labNetwork(lab).hosts).find((h) => h.os === 'linux')!.id;
    expect(ranIt(run(labNetwork(lab), host + ': lss -l /etc'), '^ls', host)).toBe(false);
    expect(ranIt(run(labNetwork(lab), host + ': ls -l /etc'), '^ls', host)).toBe(true);
  });

  it('still grades a session saved before the engine recorded this', () => {
    const net = run(startCli(), 'enable', 'show ip intttterface brief');
    delete net.devices[net.primary].acceptedHistory;
    expect(ranIt(net, '^(do )?show ip int')).toBe(true);
  });
});
