import type { Lab } from '../types';
import { DB, LIBRARY, sqlSite } from './sql-site';

const MODULE = 'sql-query';

export const sqlQueryLabs: Lab[] = [
  {
    id: 'db-01-first-query',
    moduleId: MODULE,
    order: 1,
    title: 'Your First Query',
    difficulty: 'Beginner',
    estimatedMinutes: 6,
    description: 'Meet the psql prompt, find out what is in the database, and read a table.',
    scenario:
      'You are connected to shop, the database behind a small coffee-equipment business. The prompt reads shop=#, which tells you the database you are attached to. Everything you type is SQL, and every statement ends with a semicolon: without one, psql assumes you have more to say and waits, showing shop-# instead.\n\nStart by finding your way around. \\dt lists the tables. \\d products describes one of them, column by column. Then read the products table in full with SELECT * FROM products; and finally ask for just the two columns you care about, the name and the price.',
    concepts: ['The psql prompt', '\\dt and \\d', 'SELECT * FROM table', 'Choosing columns', 'The semicolon'],
    hints: [
      'Backslash commands are psql’s own and need no semicolon. Type \\dt on its own line.',
      '\\d products prints every column of products with its type.',
      'SELECT * FROM products; reads every column of every row. The * means "all columns".',
      'Name the columns you want instead of the star: SELECT name, price FROM products;',
    ],
    createState: () => sqlSite(),
    objectives: [
      { id: 'tables', label: 'List the tables in the database', checks: [{ type: 'command', device: DB, pattern: '^\\\\dt$', label: 'Run \\dt' }] },
      { id: 'describe', label: 'Describe the products table', checks: [{ type: 'command', device: DB, pattern: '^\\\\d\\s+products$', label: 'Run \\d products' }] },
      { id: 'all', label: 'Read every column of every product', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT * FROM products', label: 'A query returned all 8 products in full' }] },
      { id: 'columns', label: 'Read just the name and price', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT name, price FROM products', label: 'A query returned the name and price of all 8 products' }] },
    ],
  },
  {
    id: 'db-02-choose-rows',
    moduleId: MODULE,
    order: 2,
    title: 'Choose the Rows',
    difficulty: 'Beginner',
    estimatedMinutes: 8,
    description: 'Filter with WHERE: equality, comparison, IN, LIKE and BETWEEN.',
    scenario:
      'A table with eight rows is easy to read whole. A real one is not, so you say which rows you want with WHERE.\n\nThe shop needs five answers. Which customers are in London. Which products cost more than 50. Which products are in the coffee or tableware categories, asked with IN rather than two conditions. Which products have "Beans" in the name, asked with LIKE and a % wildcard. And which orders were placed during February 2026, asked with BETWEEN.',
    concepts: ['WHERE', 'Comparison operators', 'IN', 'LIKE and %', 'BETWEEN', 'Quoting text and dates'],
    hints: [
      'Text and dates go in single quotes; numbers do not. SELECT name FROM customers WHERE city = \'London\';',
      'IN takes a list: WHERE category IN (\'coffee\', \'tableware\'). It is shorter than category = \'coffee\' OR category = \'tableware\'.',
      'LIKE matches a pattern where % stands for any run of characters: WHERE name LIKE \'%Beans%\'.',
      'BETWEEN includes both ends: WHERE placed BETWEEN \'2026-02-01\' AND \'2026-02-28\'.',
    ],
    createState: () => sqlSite(),
    objectives: [
      { id: 'london', label: 'Find the customers in London', checks: [{ type: 'sql-answer', device: DB, sql: "SELECT name FROM customers WHERE city = 'London'", label: 'A query returned Ada Lovelace and Cleo Marsh' }] },
      { id: 'expensive', label: 'Find the products costing more than 50', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT name, price FROM products WHERE price > 50', label: 'A query returned the two products over 50' }] },
      { id: 'categories', label: 'Find the coffee and tableware products with IN', checks: [{ type: 'sql-answer', device: DB, sql: "SELECT name FROM products WHERE category IN ('coffee', 'tableware')", label: 'A query returned the 5 coffee and tableware products' }, { type: 'sql-ran', device: DB, pattern: '\\bIN\\s*\\(', label: 'Used IN' }] },
      { id: 'beans', label: 'Find the products with Beans in the name', checks: [{ type: 'sql-answer', device: DB, sql: "SELECT name FROM products WHERE name LIKE '%Beans%'", label: 'A query returned the two bean products' }, { type: 'sql-ran', device: DB, pattern: '\\bI?LIKE\\b', label: 'Used LIKE' }] },
      { id: 'february', label: 'Find the orders placed in February 2026', checks: [{ type: 'sql-answer', device: DB, sql: "SELECT id FROM orders WHERE placed BETWEEN '2026-02-01' AND '2026-02-28'", label: 'A query returned the 5 February orders' }] },
    ],
  },
  {
    id: 'db-03-sort-and-limit',
    moduleId: MODULE,
    order: 3,
    title: 'Sort and Trim',
    difficulty: 'Beginner',
    estimatedMinutes: 7,
    description: 'Put rows in order with ORDER BY, take the top few with LIMIT, and remove repeats with DISTINCT.',
    scenario:
      'Rows come back in whatever order the database finds them, which is not an order you can rely on. ORDER BY fixes that, and once rows are in order, LIMIT takes only the first few.\n\nProduce the price list cheapest first. Then the three most expensive products, most expensive first. Then the list of categories the shop sells, with each name appearing once. Finally the three newest customers, newest first.',
    concepts: ['ORDER BY', 'ASC and DESC', 'LIMIT', 'DISTINCT'],
    hints: [
      'ORDER BY price sorts ascending; add DESC for the other direction.',
      'LIMIT goes last: SELECT name, price FROM products ORDER BY price DESC LIMIT 3;',
      'DISTINCT comes straight after SELECT and removes duplicate rows: SELECT DISTINCT category FROM products;',
      'Newest first means the largest date first, so ORDER BY joined DESC.',
    ],
    createState: () => sqlSite(),
    objectives: [
      { id: 'cheapest', label: 'List the products cheapest first', checks: [{ type: 'sql-answer', device: DB, ordered: true, sql: 'SELECT name, price FROM products ORDER BY price', label: 'A query returned all 8 products in price order' }] },
      { id: 'top3', label: 'Show the three most expensive products', checks: [{ type: 'sql-answer', device: DB, ordered: true, sql: 'SELECT name, price FROM products ORDER BY price DESC LIMIT 3', label: 'A query returned the top 3, dearest first' }] },
      { id: 'categories', label: 'List each category once', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT DISTINCT category FROM products', label: 'A query returned the 3 categories' }] },
      { id: 'newest', label: 'Show the three newest customers', checks: [{ type: 'sql-answer', device: DB, ordered: true, sql: 'SELECT name, joined FROM customers ORDER BY joined DESC LIMIT 3', label: 'A query returned the 3 most recent joiners, newest first' }] },
    ],
  },
  {
    id: 'db-04-missing-values',
    moduleId: MODULE,
    order: 4,
    title: 'The Value That Is Not There',
    difficulty: 'Beginner',
    estimatedMinutes: 7,
    description: 'Work with NULL: why comparing to it never matches, how to test for it, and how to substitute something readable.',
    scenario:
      'Two customers are missing information: one has no email address on file and one has no city. The database stores that absence as NULL, which is not an empty string and not zero. It means "unknown".\n\nThat has a consequence people trip over constantly: WHERE email = NULL returns nothing at all, because comparing anything to an unknown gives an unknown answer, and a WHERE clause keeps only rows where the answer is true. Try it and see, then ask the question properly with IS NULL.\n\nFind the customer with no email, then everyone who does have one, then count how many customers have a city recorded, and finally produce a list of every customer with their city, showing "unknown" where there is none.',
    concepts: ['NULL means unknown', 'IS NULL and IS NOT NULL', 'Why = NULL never matches', 'COALESCE'],
    hints: [
      'Run SELECT name FROM customers WHERE email = NULL; first. It returns no rows, and that is the lesson.',
      'The working form is IS NULL: SELECT name FROM customers WHERE email IS NULL;',
      'count(*) counts rows: SELECT count(*) FROM customers WHERE city IS NOT NULL;',
      "coalesce takes the first argument that is not NULL: SELECT name, coalesce(city, 'unknown') FROM customers;",
    ],
    createState: () => sqlSite(),
    objectives: [
      { id: 'tryit', label: 'See for yourself that = NULL matches nothing', checks: [{ type: 'sql-ran', device: DB, pattern: '=\\s*NULL', label: 'Compared a column to NULL' }] },
      { id: 'noemail', label: 'Find the customer with no email address', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT name FROM customers WHERE email IS NULL', label: 'A query returned Cleo Marsh' }] },
      { id: 'hasemail', label: 'Find the customers who do have one', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT name FROM customers WHERE email IS NOT NULL', label: 'A query returned the other 5 customers' }] },
      { id: 'count', label: 'Count the customers with a city on file', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT count(*) FROM customers WHERE city IS NOT NULL', label: 'A query returned 5' }] },
      { id: 'coalesce', label: 'List every customer with a readable city', checks: [{ type: 'sql-answer', device: DB, sql: "SELECT name, coalesce(city, 'unknown') FROM customers", label: 'A query returned all 6 customers with no blank city' }] },
    ],
  },
  {
    id: 'db-21-compute-and-name',
    moduleId: MODULE,
    order: 5,
    title: 'Compute and Name',
    difficulty: 'Beginner',
    estimatedMinutes: 9,
    description: 'Calculate new columns from old ones, label them with AS, and meet the division that throws away the remainder.',
    scenario:
      'A query does not have to return what is stored. It can return anything you can work out from it, so the arithmetic lives in the database rather than in a spreadsheet somebody forgot to update.\n\nStart with prices including twenty per cent VAT, rounded to two decimals, and give the new column a name with AS. Without a name the database calls it something unhelpful.\n\nThen a trap worth meeting on purpose. Ask how many sets of three each product makes: stock divided by 3. The burr grinder has eleven in stock, and the answer comes back as 3, not 3.67. Dividing one whole number by another gives a whole number and the remainder is simply dropped. Ask again with stock::numeric / 3 and the real answer appears.\n\nFinish with two more shapes: a price band for each product using CASE, and a single readable label per product made by joining text together with ||.',
    concepts: ['Computed columns', 'AS', 'round()', 'Integer division', 'Casting with ::', 'CASE WHEN', 'Concatenation with ||'],
    hints: [
      'SELECT name, round(price * 1.2, 2) AS with_vat FROM products;',
      'SELECT name, stock / 3 FROM products; gives whole numbers only. Compare it with round(stock::numeric / 3, 2).',
      "CASE WHEN price >= 100 THEN 'premium' WHEN price >= 20 THEN 'standard' ELSE 'budget' END, and remember the END.",
      "|| glues text together: name || ' (' || category || ')'.",
    ],
    createState: () => sqlSite(),
    objectives: [
      { id: 'vat', label: 'Show every price including VAT', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT name, round(price * 1.2, 2) FROM products', label: 'A query returned all 8 prices with VAT added' }] },
      { id: 'whole', label: 'See whole-number division drop the remainder', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT name, stock / 3 FROM products', label: 'A query returned the truncated sets of three' }] },
      { id: 'exact', label: 'Ask again and get the real answer', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT name, round(stock::numeric / 3, 2) FROM products', label: 'A query returned the same sums to two decimals' }] },
      { id: 'bands', label: 'Put each product in a price band', checks: [{ type: 'sql-answer', device: DB, sql: "SELECT name, CASE WHEN price >= 100 THEN 'premium' WHEN price >= 20 THEN 'standard' ELSE 'budget' END FROM products", label: 'A query banded all 8 products' }] },
      { id: 'label', label: 'Build one readable label per product', checks: [{ type: 'sql-answer', device: DB, sql: "SELECT name || ' (' || category || ')' FROM products", label: 'A query returned 8 labels of the form Name (category)' }] },
    ],
  },
  {
    id: 'db-22-read-a-schema',
    moduleId: MODULE,
    order: 6,
    title: 'Read a Schema You Did Not Write',
    difficulty: 'Beginner',
    estimatedMinutes: 9,
    description: 'Open an unfamiliar database, work out how its tables relate, and answer three questions about it.',
    scenario:
      'This is not the shop. You have been handed a library database you have never seen, which is the normal way of meeting one.\n\nThe method is always the same. \\dt tells you which tables exist. \\d on each one tells you its columns and, at the bottom, its foreign keys, and those are what tell you how the tables fit together. A column called book_id that references books is the whole story of the relationship.\n\nRead the three tables, then answer the questions the librarian actually has. Which books has nobody ever borrowed? What is out on loan right now, and who has it? And who borrows the most?\n\nOne column deserves attention: a loan that has not come back yet has no return date, so returned is NULL. That is how you tell what is still out.',
    concepts: ['Exploring an unfamiliar database', '\\dt and \\d', 'Reading foreign keys', 'NULL as "has not happened yet"'],
    hints: [
      'Start with \\dt, then \\d members, \\d books and \\d loans.',
      'The foreign keys listed under \\d loans tell you that a loan belongs to one book and one member.',
      'A book nobody has borrowed has no matching row in loans: use NOT EXISTS or a LEFT JOIN with a NULL test.',
      'Still out means returned IS NULL. Join loans to books and members to say which book and who has it.',
    ],
    createState: () => sqlSite({ setup: LIBRARY, database: 'library' }),
    objectives: [
      { id: 'explore', label: 'Read the schema before querying it', checks: [{ type: 'command', device: DB, pattern: '^\\\\dt$', label: 'Run \\dt' }, { type: 'command', device: DB, pattern: '^\\\\d\\s+loans$', label: 'Run \\d loans' }] },
      { id: 'never', label: 'Find the book nobody has borrowed', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT title FROM books b WHERE NOT EXISTS (SELECT 1 FROM loans l WHERE l.book_id = b.id)', label: 'A query returned the 1 unborrowed book' }] },
      { id: 'out', label: 'Find what is out on loan, and who has it', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT b.title, m.name FROM loans l JOIN books b ON b.id = l.book_id JOIN members m ON m.id = l.member_id WHERE l.returned IS NULL', label: 'A query returned the 2 open loans with their borrowers' }] },
      { id: 'busiest', label: 'Count the loans each member has taken', checks: [{ type: 'sql-answer', device: DB, sql: 'SELECT m.name, count(*) FROM members m JOIN loans l ON l.member_id = m.id GROUP BY m.name', label: 'A query counted loans per member' }] },
    ],
  },
];
